// Package realtime provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package realtime

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthType.
const (
	AuthTypeAUTH AuthType = "AUTH"
)

// Valid indicates whether the value is a known member of the AuthType enum.
func (e AuthType) Valid() bool {
	switch e {
	case AuthTypeAUTH:
		return true
	default:
		return false
	}
}

// Defines values for BlindPostedEventBlind.
const (
	BlindPostedEventBlindBIG   BlindPostedEventBlind = "BIG"
	BlindPostedEventBlindSMALL BlindPostedEventBlind = "SMALL"
)

// Valid indicates whether the value is a known member of the BlindPostedEventBlind enum.
func (e BlindPostedEventBlind) Valid() bool {
	switch e {
	case BlindPostedEventBlindBIG:
		return true
	case BlindPostedEventBlindSMALL:
		return true
	default:
		return false
	}
}

// Defines values for BlindPostedEventKind.
const (
	BlindPostedEventKindBLINDPOSTED BlindPostedEventKind = "BLIND_POSTED"
)

// Valid indicates whether the value is a known member of the BlindPostedEventKind enum.
func (e BlindPostedEventKind) Valid() bool {
	switch e {
	case BlindPostedEventKindBLINDPOSTED:
		return true
	default:
		return false
	}
}

// Defines values for CardsRevealedEventKind.
const (
	CardsRevealedEventKindCARDSREVEALED CardsRevealedEventKind = "CARDS_REVEALED"
)

// Valid indicates whether the value is a known member of the CardsRevealedEventKind enum.
func (e CardsRevealedEventKind) Valid() bool {
	switch e {
	case CardsRevealedEventKindCARDSREVEALED:
		return true
	default:
		return false
	}
}

// Defines values for ChatEmoji.
const (
	ChatEmojiEmpty ChatEmoji = "👍"
	ChatEmojiN1    ChatEmoji = "👏"
	ChatEmojiN10   ChatEmoji = "🙏"
	ChatEmojiN11   ChatEmoji = "💪"
	ChatEmojiN2    ChatEmoji = "😂"
	ChatEmojiN3    ChatEmoji = "😮"
	ChatEmojiN4    ChatEmoji = "😢"
	ChatEmojiN5    ChatEmoji = "😡"
	ChatEmojiN6    ChatEmoji = "🔥"
	ChatEmojiN7    ChatEmoji = "🎉"
	ChatEmojiN8    ChatEmoji = "🤝"
	ChatEmojiN9    ChatEmoji = "😎"
)

// Valid indicates whether the value is a known member of the ChatEmoji enum.
func (e ChatEmoji) Valid() bool {
	switch e {
	case ChatEmojiEmpty:
		return true
	case ChatEmojiN1:
		return true
	case ChatEmojiN10:
		return true
	case ChatEmojiN11:
		return true
	case ChatEmojiN2:
		return true
	case ChatEmojiN3:
		return true
	case ChatEmojiN4:
		return true
	case ChatEmojiN5:
		return true
	case ChatEmojiN6:
		return true
	case ChatEmojiN7:
		return true
	case ChatEmojiN8:
		return true
	case ChatEmojiN9:
		return true
	default:
		return false
	}
}

// Defines values for ChatHiddenFrameType.
const (
	ChatHiddenFrameTypeCHATHIDDEN ChatHiddenFrameType = "CHAT_HIDDEN"
)

// Valid indicates whether the value is a known member of the ChatHiddenFrameType enum.
func (e ChatHiddenFrameType) Valid() bool {
	switch e {
	case ChatHiddenFrameTypeCHATHIDDEN:
		return true
	default:
		return false
	}
}

// Defines values for ChatMessageKind.
const (
	ChatMessageKindMESSAGE  ChatMessageKind = "MESSAGE"
	ChatMessageKindREACTION ChatMessageKind = "REACTION"
)

// Valid indicates whether the value is a known member of the ChatMessageKind enum.
func (e ChatMessageKind) Valid() bool {
	switch e {
	case ChatMessageKindMESSAGE:
		return true
	case ChatMessageKindREACTION:
		return true
	default:
		return false
	}
}

// Defines values for ChatMessageFrameType.
const (
	ChatMessageFrameTypeCHATMESSAGE ChatMessageFrameType = "CHAT_MESSAGE"
)

// Valid indicates whether the value is a known member of the ChatMessageFrameType enum.
func (e ChatMessageFrameType) Valid() bool {
	switch e {
	case ChatMessageFrameTypeCHATMESSAGE:
		return true
	default:
		return false
	}
}

// Defines values for ChatSendType.
const (
	ChatSendTypeCHATSEND ChatSendType = "CHAT_SEND"
)

// Valid indicates whether the value is a known member of the ChatSendType enum.
func (e ChatSendType) Valid() bool {
	switch e {
	case ChatSendTypeCHATSEND:
		return true
	default:
		return false
	}
}

// Defines values for ClientMessageType.
const (
	ClientMessageTypeAUTH             ClientMessageType = "AUTH"
	ClientMessageTypeCHATSEND         ClientMessageType = "CHAT_SEND"
	ClientMessageTypeCOMMAND          ClientMessageType = "COMMAND"
	ClientMessageTypeHELLO            ClientMessageType = "HELLO"
	ClientMessageTypePING             ClientMessageType = "PING"
	ClientMessageTypePONG             ClientMessageType = "PONG"
	ClientMessageTypeSUBSCRIBETABLE   ClientMessageType = "SUBSCRIBE_TABLE"
	ClientMessageTypeUNSUBSCRIBETABLE ClientMessageType = "UNSUBSCRIBE_TABLE"
)

// Valid indicates whether the value is a known member of the ClientMessageType enum.
func (e ClientMessageType) Valid() bool {
	switch e {
	case ClientMessageTypeAUTH:
		return true
	case ClientMessageTypeCHATSEND:
		return true
	case ClientMessageTypeCOMMAND:
		return true
	case ClientMessageTypeHELLO:
		return true
	case ClientMessageTypePING:
		return true
	case ClientMessageTypePONG:
		return true
	case ClientMessageTypeSUBSCRIBETABLE:
		return true
	case ClientMessageTypeUNSUBSCRIBETABLE:
		return true
	default:
		return false
	}
}

// Defines values for CommandType.
const (
	CommandTypeCOMMAND CommandType = "COMMAND"
)

// Valid indicates whether the value is a known member of the CommandType enum.
func (e CommandType) Valid() bool {
	switch e {
	case CommandTypeCOMMAND:
		return true
	default:
		return false
	}
}

// Defines values for CommandPayloadKind.
const (
	CommandPayloadKindALLIN  CommandPayloadKind = "ALL_IN"
	CommandPayloadKindBET    CommandPayloadKind = "BET"
	CommandPayloadKindCALL   CommandPayloadKind = "CALL"
	CommandPayloadKindCHECK  CommandPayloadKind = "CHECK"
	CommandPayloadKindFOLD   CommandPayloadKind = "FOLD"
	CommandPayloadKindRAISE  CommandPayloadKind = "RAISE"
	CommandPayloadKindSITIN  CommandPayloadKind = "SIT_IN"
	CommandPayloadKindSITOUT CommandPayloadKind = "SIT_OUT"
)

// Valid indicates whether the value is a known member of the CommandPayloadKind enum.
func (e CommandPayloadKind) Valid() bool {
	switch e {
	case CommandPayloadKindALLIN:
		return true
	case CommandPayloadKindBET:
		return true
	case CommandPayloadKindCALL:
		return true
	case CommandPayloadKindCHECK:
		return true
	case CommandPayloadKindFOLD:
		return true
	case CommandPayloadKindRAISE:
		return true
	case CommandPayloadKindSITIN:
		return true
	case CommandPayloadKindSITOUT:
		return true
	default:
		return false
	}
}

// Defines values for CommandResultType.
const (
	CommandResultTypeCOMMANDRESULT CommandResultType = "COMMAND_RESULT"
)

// Valid indicates whether the value is a known member of the CommandResultType enum.
func (e CommandResultType) Valid() bool {
	switch e {
	case CommandResultTypeCOMMANDRESULT:
		return true
	default:
		return false
	}
}

// Defines values for GameType.
const (
	GameTypeNLHE GameType = "NLHE"
	GameTypePLO  GameType = "PLO"
)

// Valid indicates whether the value is a known member of the GameType enum.
func (e GameType) Valid() bool {
	switch e {
	case GameTypeNLHE:
		return true
	case GameTypePLO:
		return true
	default:
		return false
	}
}

// Defines values for HandCompletedEventKind.
const (
	HandCompletedEventKindHANDCOMPLETED HandCompletedEventKind = "HAND_COMPLETED"
)

// Valid indicates whether the value is a known member of the HandCompletedEventKind enum.
func (e HandCompletedEventKind) Valid() bool {
	switch e {
	case HandCompletedEventKindHANDCOMPLETED:
		return true
	default:
		return false
	}
}

// Defines values for HandStartedEventKind.
const (
	HandStartedEventKindHANDSTARTED HandStartedEventKind = "HAND_STARTED"
)

// Valid indicates whether the value is a known member of the HandStartedEventKind enum.
func (e HandStartedEventKind) Valid() bool {
	switch e {
	case HandStartedEventKindHANDSTARTED:
		return true
	default:
		return false
	}
}

// Defines values for HandViewStreet.
const (
	HandViewStreetCOMPLETE HandViewStreet = "COMPLETE"
	HandViewStreetFLOP     HandViewStreet = "FLOP"
	HandViewStreetPREFLOP  HandViewStreet = "PREFLOP"
	HandViewStreetRIVER    HandViewStreet = "RIVER"
	HandViewStreetSHOWDOWN HandViewStreet = "SHOWDOWN"
	HandViewStreetTURN     HandViewStreet = "TURN"
)

// Valid indicates whether the value is a known member of the HandViewStreet enum.
func (e HandViewStreet) Valid() bool {
	switch e {
	case HandViewStreetCOMPLETE:
		return true
	case HandViewStreetFLOP:
		return true
	case HandViewStreetPREFLOP:
		return true
	case HandViewStreetRIVER:
		return true
	case HandViewStreetSHOWDOWN:
		return true
	case HandViewStreetTURN:
		return true
	default:
		return false
	}
}

// Defines values for HandVoidedEventKind.
const (
	HandVoidedEventKindHANDVOIDED HandVoidedEventKind = "HAND_VOIDED"
)

// Valid indicates whether the value is a known member of the HandVoidedEventKind enum.
func (e HandVoidedEventKind) Valid() bool {
	switch e {
	case HandVoidedEventKindHANDVOIDED:
		return true
	default:
		return false
	}
}

// Defines values for HelloType.
const (
	HelloTypeHELLO HelloType = "HELLO"
)

// Valid indicates whether the value is a known member of the HelloType enum.
func (e HelloType) Valid() bool {
	switch e {
	case HelloTypeHELLO:
		return true
	default:
		return false
	}
}

// Defines values for HoleCardsDealtEventKind.
const (
	HoleCardsDealtEventKindHOLECARDSDEALT HoleCardsDealtEventKind = "HOLE_CARDS_DEALT"
)

// Valid indicates whether the value is a known member of the HoleCardsDealtEventKind enum.
func (e HoleCardsDealtEventKind) Valid() bool {
	switch e {
	case HoleCardsDealtEventKindHOLECARDSDEALT:
		return true
	default:
		return false
	}
}

// Defines values for LegalActionKind.
const (
	LegalActionKindALLIN LegalActionKind = "ALL_IN"
	LegalActionKindBET   LegalActionKind = "BET"
	LegalActionKindCALL  LegalActionKind = "CALL"
	LegalActionKindCHECK LegalActionKind = "CHECK"
	LegalActionKindFOLD  LegalActionKind = "FOLD"
	LegalActionKindRAISE LegalActionKind = "RAISE"
)

// Valid indicates whether the value is a known member of the LegalActionKind enum.
func (e LegalActionKind) Valid() bool {
	switch e {
	case LegalActionKindALLIN:
		return true
	case LegalActionKindBET:
		return true
	case LegalActionKindCALL:
		return true
	case LegalActionKindCHECK:
		return true
	case LegalActionKindFOLD:
		return true
	case LegalActionKindRAISE:
		return true
	default:
		return false
	}
}

// Defines values for PingType.
const (
	PingTypePING PingType = "PING"
)

// Valid indicates whether the value is a known member of the PingType enum.
func (e PingType) Valid() bool {
	switch e {
	case PingTypePING:
		return true
	default:
		return false
	}
}

// Defines values for PlayerActedEventAction.
const (
	PlayerActedEventActionBET   PlayerActedEventAction = "BET"
	PlayerActedEventActionCALL  PlayerActedEventAction = "CALL"
	PlayerActedEventActionCHECK PlayerActedEventAction = "CHECK"
	PlayerActedEventActionFOLD  PlayerActedEventAction = "FOLD"
	PlayerActedEventActionRAISE PlayerActedEventAction = "RAISE"
)

// Valid indicates whether the value is a known member of the PlayerActedEventAction enum.
func (e PlayerActedEventAction) Valid() bool {
	switch e {
	case PlayerActedEventActionBET:
		return true
	case PlayerActedEventActionCALL:
		return true
	case PlayerActedEventActionCHECK:
		return true
	case PlayerActedEventActionFOLD:
		return true
	case PlayerActedEventActionRAISE:
		return true
	default:
		return false
	}
}

// Defines values for PlayerActedEventKind.
const (
	PlayerActedEventKindPLAYERACTED PlayerActedEventKind = "PLAYER_ACTED"
)

// Valid indicates whether the value is a known member of the PlayerActedEventKind enum.
func (e PlayerActedEventKind) Valid() bool {
	switch e {
	case PlayerActedEventKindPLAYERACTED:
		return true
	default:
		return false
	}
}

// Defines values for PlayerLeftEventKind.
const (
	PlayerLeftEventKindPLAYERLEFT PlayerLeftEventKind = "PLAYER_LEFT"
)

// Valid indicates whether the value is a known member of the PlayerLeftEventKind enum.
func (e PlayerLeftEventKind) Valid() bool {
	switch e {
	case PlayerLeftEventKindPLAYERLEFT:
		return true
	default:
		return false
	}
}

// Defines values for PlayerLeftEventReason.
const (
	PlayerLeftEventReasonBUSTED      PlayerLeftEventReason = "BUSTED"
	PlayerLeftEventReasonELIMINATED  PlayerLeftEventReason = "ELIMINATED"
	PlayerLeftEventReasonFINISHED    PlayerLeftEventReason = "FINISHED"
	PlayerLeftEventReasonLEFT        PlayerLeftEventReason = "LEFT"
	PlayerLeftEventReasonMOVED       PlayerLeftEventReason = "MOVED"
	PlayerLeftEventReasonTABLECLOSED PlayerLeftEventReason = "TABLE_CLOSED"
)

// Valid indicates whether the value is a known member of the PlayerLeftEventReason enum.
func (e PlayerLeftEventReason) Valid() bool {
	switch e {
	case PlayerLeftEventReasonBUSTED:
		return true
	case PlayerLeftEventReasonELIMINATED:
		return true
	case PlayerLeftEventReasonFINISHED:
		return true
	case PlayerLeftEventReasonLEFT:
		return true
	case PlayerLeftEventReasonMOVED:
		return true
	case PlayerLeftEventReasonTABLECLOSED:
		return true
	default:
		return false
	}
}

// Defines values for PlayerSeatedEventKind.
const (
	PlayerSeatedEventKindPLAYERSEATED PlayerSeatedEventKind = "PLAYER_SEATED"
)

// Valid indicates whether the value is a known member of the PlayerSeatedEventKind enum.
func (e PlayerSeatedEventKind) Valid() bool {
	switch e {
	case PlayerSeatedEventKindPLAYERSEATED:
		return true
	default:
		return false
	}
}

// Defines values for PlayerSittingOutEventKind.
const (
	PlayerSittingOutEventKindPLAYERSITTINGOUT PlayerSittingOutEventKind = "PLAYER_SITTING_OUT"
)

// Valid indicates whether the value is a known member of the PlayerSittingOutEventKind enum.
func (e PlayerSittingOutEventKind) Valid() bool {
	switch e {
	case PlayerSittingOutEventKindPLAYERSITTINGOUT:
		return true
	default:
		return false
	}
}

// Defines values for PlayerSittingOutEventReason.
const (
	PlayerSittingOutEventReasonBUSTED   PlayerSittingOutEventReason = "BUSTED"
	PlayerSittingOutEventReasonLEAVING  PlayerSittingOutEventReason = "LEAVING"
	PlayerSittingOutEventReasonREQUEST  PlayerSittingOutEventReason = "REQUEST"
	PlayerSittingOutEventReasonTIMEOUTS PlayerSittingOutEventReason = "TIMEOUTS"
	PlayerSittingOutEventReasonTOPUP    PlayerSittingOutEventReason = "TOP_UP"
)

// Valid indicates whether the value is a known member of the PlayerSittingOutEventReason enum.
func (e PlayerSittingOutEventReason) Valid() bool {
	switch e {
	case PlayerSittingOutEventReasonBUSTED:
		return true
	case PlayerSittingOutEventReasonLEAVING:
		return true
	case PlayerSittingOutEventReasonREQUEST:
		return true
	case PlayerSittingOutEventReasonTIMEOUTS:
		return true
	case PlayerSittingOutEventReasonTOPUP:
		return true
	default:
		return false
	}
}

// Defines values for PlayerToppedUpEventKind.
const (
	PlayerToppedUpEventKindPLAYERTOPPEDUP PlayerToppedUpEventKind = "PLAYER_TOPPED_UP"
)

// Valid indicates whether the value is a known member of the PlayerToppedUpEventKind enum.
func (e PlayerToppedUpEventKind) Valid() bool {
	switch e {
	case PlayerToppedUpEventKindPLAYERTOPPEDUP:
		return true
	default:
		return false
	}
}

// Defines values for PongType.
const (
	PongTypePONG PongType = "PONG"
)

// Valid indicates whether the value is a known member of the PongType enum.
func (e PongType) Valid() bool {
	switch e {
	case PongTypePONG:
		return true
	default:
		return false
	}
}

// Defines values for PotAwardedEventKind.
const (
	PotAwardedEventKindPOTAWARDED PotAwardedEventKind = "POT_AWARDED"
)

// Valid indicates whether the value is a known member of the PotAwardedEventKind enum.
func (e PotAwardedEventKind) Valid() bool {
	switch e {
	case PotAwardedEventKindPOTAWARDED:
		return true
	default:
		return false
	}
}

// Defines values for ProtocolErrorType.
const (
	ProtocolErrorTypeERROR ProtocolErrorType = "ERROR"
)

// Valid indicates whether the value is a known member of the ProtocolErrorType enum.
func (e ProtocolErrorType) Valid() bool {
	switch e {
	case ProtocolErrorTypeERROR:
		return true
	default:
		return false
	}
}

// Defines values for ResyncRequiredReason.
const (
	ResyncRequiredReasonEVENTSNOTRETAINED ResyncRequiredReason = "EVENTS_NOT_RETAINED"
	ResyncRequiredReasonFEEDRESET         ResyncRequiredReason = "FEED_RESET"
	ResyncRequiredReasonSEQUENCEGAP       ResyncRequiredReason = "SEQUENCE_GAP"
)

// Valid indicates whether the value is a known member of the ResyncRequiredReason enum.
func (e ResyncRequiredReason) Valid() bool {
	switch e {
	case ResyncRequiredReasonEVENTSNOTRETAINED:
		return true
	case ResyncRequiredReasonFEEDRESET:
		return true
	case ResyncRequiredReasonSEQUENCEGAP:
		return true
	default:
		return false
	}
}

// Defines values for ResyncRequiredType.
const (
	ResyncRequiredTypeRESYNCREQUIRED ResyncRequiredType = "RESYNC_REQUIRED"
)

// Valid indicates whether the value is a known member of the ResyncRequiredType enum.
func (e ResyncRequiredType) Valid() bool {
	switch e {
	case ResyncRequiredTypeRESYNCREQUIRED:
		return true
	default:
		return false
	}
}

// Defines values for ServerMessageType.
const (
	ServerMessageTypeCHATHIDDEN     ServerMessageType = "CHAT_HIDDEN"
	ServerMessageTypeCHATMESSAGE    ServerMessageType = "CHAT_MESSAGE"
	ServerMessageTypeCOMMANDRESULT  ServerMessageType = "COMMAND_RESULT"
	ServerMessageTypeERROR          ServerMessageType = "ERROR"
	ServerMessageTypePING           ServerMessageType = "PING"
	ServerMessageTypePONG           ServerMessageType = "PONG"
	ServerMessageTypeRESYNCREQUIRED ServerMessageType = "RESYNC_REQUIRED"
	ServerMessageTypeSUBSCRIBED     ServerMessageType = "SUBSCRIBED"
	ServerMessageTypeTABLEEVENT     ServerMessageType = "TABLE_EVENT"
	ServerMessageTypeTABLESNAPSHOT  ServerMessageType = "TABLE_SNAPSHOT"
	ServerMessageTypeWELCOME        ServerMessageType = "WELCOME"
)

// Valid indicates whether the value is a known member of the ServerMessageType enum.
func (e ServerMessageType) Valid() bool {
	switch e {
	case ServerMessageTypeCHATHIDDEN:
		return true
	case ServerMessageTypeCHATMESSAGE:
		return true
	case ServerMessageTypeCOMMANDRESULT:
		return true
	case ServerMessageTypeERROR:
		return true
	case ServerMessageTypePING:
		return true
	case ServerMessageTypePONG:
		return true
	case ServerMessageTypeRESYNCREQUIRED:
		return true
	case ServerMessageTypeSUBSCRIBED:
		return true
	case ServerMessageTypeTABLEEVENT:
		return true
	case ServerMessageTypeTABLESNAPSHOT:
		return true
	case ServerMessageTypeWELCOME:
		return true
	default:
		return false
	}
}

// Defines values for StreetDealtEventKind.
const (
	StreetDealtEventKindSTREETDEALT StreetDealtEventKind = "STREET_DEALT"
)

// Valid indicates whether the value is a known member of the StreetDealtEventKind enum.
func (e StreetDealtEventKind) Valid() bool {
	switch e {
	case StreetDealtEventKindSTREETDEALT:
		return true
	default:
		return false
	}
}

// Defines values for StreetDealtEventStreet.
const (
	StreetDealtEventStreetFLOP  StreetDealtEventStreet = "FLOP"
	StreetDealtEventStreetRIVER StreetDealtEventStreet = "RIVER"
	StreetDealtEventStreetTURN  StreetDealtEventStreet = "TURN"
)

// Valid indicates whether the value is a known member of the StreetDealtEventStreet enum.
func (e StreetDealtEventStreet) Valid() bool {
	switch e {
	case StreetDealtEventStreetFLOP:
		return true
	case StreetDealtEventStreetRIVER:
		return true
	case StreetDealtEventStreetTURN:
		return true
	default:
		return false
	}
}

// Defines values for SubscribeTableType.
const (
	SubscribeTableTypeSUBSCRIBETABLE SubscribeTableType = "SUBSCRIBE_TABLE"
)

// Valid indicates whether the value is a known member of the SubscribeTableType enum.
func (e SubscribeTableType) Valid() bool {
	switch e {
	case SubscribeTableTypeSUBSCRIBETABLE:
		return true
	default:
		return false
	}
}

// Defines values for SubscribedMode.
const (
	SubscribedModeREPLAY   SubscribedMode = "REPLAY"
	SubscribedModeSNAPSHOT SubscribedMode = "SNAPSHOT"
)

// Valid indicates whether the value is a known member of the SubscribedMode enum.
func (e SubscribedMode) Valid() bool {
	switch e {
	case SubscribedModeREPLAY:
		return true
	case SubscribedModeSNAPSHOT:
		return true
	default:
		return false
	}
}

// Defines values for SubscribedType.
const (
	SubscribedTypeSUBSCRIBED SubscribedType = "SUBSCRIBED"
)

// Valid indicates whether the value is a known member of the SubscribedType enum.
func (e SubscribedType) Valid() bool {
	switch e {
	case SubscribedTypeSUBSCRIBED:
		return true
	default:
		return false
	}
}

// Defines values for TableClosedEventKind.
const (
	TableClosedEventKindTABLECLOSED TableClosedEventKind = "TABLE_CLOSED"
)

// Valid indicates whether the value is a known member of the TableClosedEventKind enum.
func (e TableClosedEventKind) Valid() bool {
	switch e {
	case TableClosedEventKindTABLECLOSED:
		return true
	default:
		return false
	}
}

// Defines values for TableEventMessageType.
const (
	TableEventMessageTypeTABLEEVENT TableEventMessageType = "TABLE_EVENT"
)

// Valid indicates whether the value is a known member of the TableEventMessageType enum.
func (e TableEventMessageType) Valid() bool {
	switch e {
	case TableEventMessageTypeTABLEEVENT:
		return true
	default:
		return false
	}
}

// Defines values for TableInfoStatus.
const (
	TableInfoStatusCLOSED TableInfoStatus = "CLOSED"
	TableInfoStatusOPEN   TableInfoStatus = "OPEN"
)

// Valid indicates whether the value is a known member of the TableInfoStatus enum.
func (e TableInfoStatus) Valid() bool {
	switch e {
	case TableInfoStatusCLOSED:
		return true
	case TableInfoStatusOPEN:
		return true
	default:
		return false
	}
}

// Defines values for TableSnapshotPhase.
const (
	TableSnapshotPhaseHANDCOMPLETE      TableSnapshotPhase = "HAND_COMPLETE"
	TableSnapshotPhaseHANDINPROGRESS    TableSnapshotPhase = "HAND_IN_PROGRESS"
	TableSnapshotPhaseWAITINGFORPLAYERS TableSnapshotPhase = "WAITING_FOR_PLAYERS"
)

// Valid indicates whether the value is a known member of the TableSnapshotPhase enum.
func (e TableSnapshotPhase) Valid() bool {
	switch e {
	case TableSnapshotPhaseHANDCOMPLETE:
		return true
	case TableSnapshotPhaseHANDINPROGRESS:
		return true
	case TableSnapshotPhaseWAITINGFORPLAYERS:
		return true
	default:
		return false
	}
}

// Defines values for TableSnapshotMessageType.
const (
	TableSnapshotMessageTypeTABLESNAPSHOT TableSnapshotMessageType = "TABLE_SNAPSHOT"
)

// Valid indicates whether the value is a known member of the TableSnapshotMessageType enum.
func (e TableSnapshotMessageType) Valid() bool {
	switch e {
	case TableSnapshotMessageTypeTABLESNAPSHOT:
		return true
	default:
		return false
	}
}

// Defines values for TimeBankStartedEventKind.
const (
	TimeBankStartedEventKindTIMEBANKSTARTED TimeBankStartedEventKind = "TIME_BANK_STARTED"
)

// Valid indicates whether the value is a known member of the TimeBankStartedEventKind enum.
func (e TimeBankStartedEventKind) Valid() bool {
	switch e {
	case TimeBankStartedEventKindTIMEBANKSTARTED:
		return true
	default:
		return false
	}
}

// Defines values for TournamentTableInfoStatus.
const (
	TournamentTableInfoStatusFINISHED TournamentTableInfoStatus = "FINISHED"
	TournamentTableInfoStatusRUNNING  TournamentTableInfoStatus = "RUNNING"
)

// Valid indicates whether the value is a known member of the TournamentTableInfoStatus enum.
func (e TournamentTableInfoStatus) Valid() bool {
	switch e {
	case TournamentTableInfoStatusFINISHED:
		return true
	case TournamentTableInfoStatusRUNNING:
		return true
	default:
		return false
	}
}

// Defines values for TurnStartedEventKind.
const (
	TurnStartedEventKindTURNSTARTED TurnStartedEventKind = "TURN_STARTED"
)

// Valid indicates whether the value is a known member of the TurnStartedEventKind enum.
func (e TurnStartedEventKind) Valid() bool {
	switch e {
	case TurnStartedEventKindTURNSTARTED:
		return true
	default:
		return false
	}
}

// Defines values for TurnStartedEventStreet.
const (
	TurnStartedEventStreetFLOP    TurnStartedEventStreet = "FLOP"
	TurnStartedEventStreetPREFLOP TurnStartedEventStreet = "PREFLOP"
	TurnStartedEventStreetRIVER   TurnStartedEventStreet = "RIVER"
	TurnStartedEventStreetTURN    TurnStartedEventStreet = "TURN"
)

// Valid indicates whether the value is a known member of the TurnStartedEventStreet enum.
func (e TurnStartedEventStreet) Valid() bool {
	switch e {
	case TurnStartedEventStreetFLOP:
		return true
	case TurnStartedEventStreetPREFLOP:
		return true
	case TurnStartedEventStreetRIVER:
		return true
	case TurnStartedEventStreetTURN:
		return true
	default:
		return false
	}
}

// Defines values for UncalledBetReturnedEventKind.
const (
	UncalledBetReturnedEventKindUNCALLEDBETRETURNED UncalledBetReturnedEventKind = "UNCALLED_BET_RETURNED"
)

// Valid indicates whether the value is a known member of the UncalledBetReturnedEventKind enum.
func (e UncalledBetReturnedEventKind) Valid() bool {
	switch e {
	case UncalledBetReturnedEventKindUNCALLEDBETRETURNED:
		return true
	default:
		return false
	}
}

// Defines values for UnsubscribeTableType.
const (
	UnsubscribeTableTypeUNSUBSCRIBETABLE UnsubscribeTableType = "UNSUBSCRIBE_TABLE"
)

// Valid indicates whether the value is a known member of the UnsubscribeTableType enum.
func (e UnsubscribeTableType) Valid() bool {
	switch e {
	case UnsubscribeTableTypeUNSUBSCRIBETABLE:
		return true
	default:
		return false
	}
}

// Defines values for WelcomeType.
const (
	WelcomeTypeWELCOME WelcomeType = "WELCOME"
)

// Valid indicates whether the value is a known member of the WelcomeType enum.
func (e WelcomeType) Valid() bool {
	switch e {
	case WelcomeTypeWELCOME:
		return true
	default:
		return false
	}
}

// Auth Re-authenticates a live connection with a fresh access token before the current one expires.
type Auth struct {
	AccessToken string   `json:"accessToken"`
	Type        AuthType `json:"type"`
}

// AuthType defines model for Auth.Type.
type AuthType string

// BlindPostedEvent defines model for BlindPostedEvent.
type BlindPostedEvent struct {
	AllIn  bool                  `json:"allIn"`
	Amount int64                 `json:"amount"`
	Blind  BlindPostedEventBlind `json:"blind"`
	Kind   BlindPostedEventKind  `json:"kind"`
	Pot    int64                 `json:"pot"`
	Seat   int                   `json:"seat"`
	Stack  int64                 `json:"stack"`
}

// BlindPostedEventBlind defines model for BlindPostedEvent.Blind.
type BlindPostedEventBlind string

// BlindPostedEventKind defines model for BlindPostedEvent.Kind.
type BlindPostedEventKind string

// Card Rank + suit, e.g. "As", "Td", "2c".
type Card = string

// CardsRevealedEvent defines model for CardsRevealedEvent.
type CardsRevealedEvent struct {
	BestFive    []Card                 `json:"bestFive"`
	Cards       []Card                 `json:"cards"`
	Description string                 `json:"description"`
	Kind        CardsRevealedEventKind `json:"kind"`
	Seat        int                    `json:"seat"`
}

// CardsRevealedEventKind defines model for CardsRevealedEvent.Kind.
type CardsRevealedEventKind string

// ChatEmoji defines model for ChatEmoji.
type ChatEmoji string

// ChatHiddenFrame Club staff hid a message after a report; clients remove it.
type ChatHiddenFrame struct {
	MessageId openapi_types.UUID  `json:"messageId"`
	TableId   openapi_types.UUID  `json:"tableId"`
	Type      ChatHiddenFrameType `json:"type"`
}

// ChatHiddenFrameType defines model for ChatHiddenFrame.Type.
type ChatHiddenFrameType string

// ChatMessage defines model for ChatMessage.
type ChatMessage struct {
	Emoji *ChatEmoji         `json:"emoji,omitempty"`
	Id    openapi_types.UUID `json:"id"`

	// Kind REACTION carries an emoji and is not kept in the history.
	Kind     ChatMessageKind    `json:"kind"`
	SentAt   time.Time          `json:"sentAt"`
	TableId  openapi_types.UUID `json:"tableId"`
	Text     *string            `json:"text,omitempty"`
	UserId   openapi_types.UUID `json:"userId"`
	Username string             `json:"username"`
}

// ChatMessageKind REACTION carries an emoji and is not kept in the history.
type ChatMessageKind string

// ChatMessageFrame defines model for ChatMessageFrame.
type ChatMessageFrame struct {
	Message ChatMessage          `json:"message"`
	TableId openapi_types.UUID   `json:"tableId"`
	Type    ChatMessageFrameType `json:"type"`
}

// ChatMessageFrameType defines model for ChatMessageFrame.Type.
type ChatMessageFrameType string

// ChatSend A chat message (text) or an emoji reaction (emoji) at a table the
// connection is subscribed to; exactly one of the two. requestId is the
// idempotency key: a resent message is stored and delivered once.
// Everyone watching the table, the sender included, receives it as
// CHAT_MESSAGE; a rejected send is answered with ERROR (CHAT_DISABLED,
// RATE_LIMITED, VALIDATION_FAILED, ...) carrying the requestId.
type ChatSend struct {
	Emoji     *ChatEmoji         `json:"emoji,omitempty"`
	RequestId openapi_types.UUID `json:"requestId"`
	TableId   openapi_types.UUID `json:"tableId"`
	Text      *string            `json:"text,omitempty"`
	Type      ChatSendType       `json:"type"`
}

// ChatSendType defines model for ChatSend.Type.
type ChatSendType string

// ClientMessageType defines model for ClientMessageType.
type ClientMessageType string

// Command Player intent. requestId (UUID) is the command's idempotency key
// (EventID): resending it never applies the action twice.
type Command struct {
	Command CommandPayload `json:"command"`

	// ExpectedSeq Last seq the client has applied; stale values are rejected with STALE_GAME_STATE.
	ExpectedSeq *int64             `json:"expectedSeq,omitempty"`
	RequestId   openapi_types.UUID `json:"requestId"`
	TableId     openapi_types.UUID `json:"tableId"`
	Type        CommandType        `json:"type"`
}

// CommandType defines model for Command.Type.
type CommandType string

// CommandError defines model for CommandError.
type CommandError struct {
	// Code An ErrorCode value from the control-api contract.
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// CommandPayload defines model for CommandPayload.
type CommandPayload struct {
	// Amount BET/RAISE "to" amount (total street commitment after the action).
	Amount *int64             `json:"amount,omitempty"`
	Kind   CommandPayloadKind `json:"kind"`
}

// CommandPayloadKind defines model for CommandPayload.Kind.
type CommandPayloadKind string

// CommandResult defines model for CommandResult.
type CommandResult struct {
	Accepted  bool               `json:"accepted"`
	Duplicate bool               `json:"duplicate"`
	Error     *CommandError      `json:"error,omitempty"`
	RequestId openapi_types.UUID `json:"requestId"`

	// Seq Seq of the first event produced by the command (or the table seq at rejection).
	Seq     int64              `json:"seq"`
	TableId openapi_types.UUID `json:"tableId"`
	Type    CommandResultType  `json:"type"`
}

// CommandResultType defines model for CommandResult.Type.
type CommandResultType string

// GameType NLHE = No-Limit Texas Hold'em (2 hole cards). PLO = Pot-Limit Omaha
// (4 hole cards; a hand uses exactly two of them and three board cards;
// bets and raises are capped at the pot).
type GameType string

// HandCompletedEvent defines model for HandCompletedEvent.
type HandCompletedEvent struct {
	Board    []Card                 `json:"board"`
	HandId   openapi_types.UUID     `json:"handId"`
	HandNo   int64                  `json:"handNo"`
	Kind     HandCompletedEventKind `json:"kind"`
	Results  []HandResult           `json:"results"`
	Showdown bool                   `json:"showdown"`
}

// HandCompletedEventKind defines model for HandCompletedEvent.Kind.
type HandCompletedEventKind string

// HandPlayer defines model for HandPlayer.
type HandPlayer struct {
	Seat  int   `json:"seat"`
	Stack int64 `json:"stack"`

	// TimeBankMs Time bank after this hand's refill.
	TimeBankMs int64              `json:"timeBankMs"`
	UserId     openapi_types.UUID `json:"userId"`
}

// HandResult defines model for HandResult.
type HandResult struct {
	Contributed int64              `json:"contributed"`
	Folded      bool               `json:"folded"`
	Net         int64              `json:"net"`
	Seat        int                `json:"seat"`
	Stack       int64              `json:"stack"`
	UserId      openapi_types.UUID `json:"userId"`
	Won         int64              `json:"won"`
}

// HandStartedEvent defines model for HandStartedEvent.
type HandStartedEvent struct {
	BigBlind       int64  `json:"bigBlind"`
	BigBlindSeat   int    `json:"bigBlindSeat"`
	ButtonSeat     int    `json:"buttonSeat"`
	DeckCommitment string `json:"deckCommitment"`

	// GameType NLHE = No-Limit Texas Hold'em (2 hole cards). PLO = Pot-Limit Omaha
	// (4 hole cards; a hand uses exactly two of them and three board cards;
	// bets and raises are capped at the pot).
	GameType       GameType             `json:"gameType"`
	HandId         openapi_types.UUID   `json:"handId"`
	HandNo         int64                `json:"handNo"`
	Kind           HandStartedEventKind `json:"kind"`
	Players        []HandPlayer         `json:"players"`
	SmallBlind     int64                `json:"smallBlind"`
	SmallBlindSeat int                  `json:"smallBlindSeat"`

	// Tournament Tournament context of a tournament table (level and blinds in effect for new hands).
	Tournament *TournamentTableInfo `json:"tournament,omitempty"`
}

// HandStartedEventKind defines model for HandStartedEvent.Kind.
type HandStartedEventKind string

// HandView defines model for HandView.
type HandView struct {
	ActionDeadline *time.Time `json:"actionDeadline"`
	BigBlindSeat   int        `json:"bigBlindSeat"`
	Board          []Card     `json:"board"`
	ButtonSeat     int        `json:"buttonSeat"`
	CurrentBet     int64      `json:"currentBet"`

	// DeckCommitment SHA-256 commitment to the deck order (audit).
	DeckCommitment string             `json:"deckCommitment"`
	HandId         openapi_types.UUID `json:"handId"`
	HandNo         int64              `json:"handNo"`
	MinRaise       int64              `json:"minRaise"`
	Pot            int64              `json:"pot"`
	SmallBlindSeat int                `json:"smallBlindSeat"`
	Street         HandViewStreet     `json:"street"`

	// ToActSeat 0 when nobody is to act.
	ToActSeat int `json:"toActSeat"`

	// TurnSeq Sequence of the TURN_STARTED event of the current turn.
	TurnSeq int64 `json:"turnSeq"`

	// UsingTimeBank The actor's turn timer ran out and actionDeadline is the end of their time bank.
	UsingTimeBank bool `json:"usingTimeBank"`
}

// HandViewStreet defines model for HandView.Street.
type HandViewStreet string

// HandVoidedEvent defines model for HandVoidedEvent.
type HandVoidedEvent struct {
	HandId openapi_types.UUID  `json:"handId"`
	HandNo int64               `json:"handNo"`
	Kind   HandVoidedEventKind `json:"kind"`
	Reason string              `json:"reason"`
}

// HandVoidedEventKind defines model for HandVoidedEvent.Kind.
type HandVoidedEventKind string

// Hello First client frame (within 10 s). Authenticates the connection.
type Hello struct {
	AccessToken   string    `json:"accessToken"`
	ClientVersion string    `json:"clientVersion"`
	DeviceId      *string   `json:"deviceId,omitempty"`
	Type          HelloType `json:"type"`
}

// HelloType defines model for Hello.Type.
type HelloType string

// HoleCardsDealtEvent defines model for HoleCardsDealtEvent.
type HoleCardsDealtEvent struct {
	Cards *[]Card                 `json:"cards,omitempty"`
	Kind  HoleCardsDealtEventKind `json:"kind"`
	Seats []int                   `json:"seats"`
}

// HoleCardsDealtEventKind defines model for HoleCardsDealtEvent.Kind.
type HoleCardsDealtEventKind string

// LegalAction defines model for LegalAction.
type LegalAction struct {
	// Amount CALL - chips to add; ALL_IN - resulting street commitment.
	Amount *int64          `json:"amount,omitempty"`
	Kind   LegalActionKind `json:"kind"`

	// MaxTo BET/RAISE maximum "to" amount (all-in, or the pot limit in PLO).
	MaxTo *int64 `json:"maxTo,omitempty"`

	// MinTo BET/RAISE minimum "to" amount.
	MinTo *int64 `json:"minTo,omitempty"`
}

// LegalActionKind defines model for LegalAction.Kind.
type LegalActionKind string

// Ping defines model for Ping.
type Ping struct {
	Nonce *string  `json:"nonce,omitempty"`
	Type  PingType `json:"type"`
}

// PingType defines model for Ping.Type.
type PingType string

// PlayerActedEvent defines model for PlayerActedEvent.
type PlayerActedEvent struct {
	Action    PlayerActedEventAction `json:"action"`
	Added     int64                  `json:"added"`
	AllIn     bool                   `json:"allIn"`
	Kind      PlayerActedEventKind   `json:"kind"`
	Pot       int64                  `json:"pot"`
	Seat      int                    `json:"seat"`
	Stack     int64                  `json:"stack"`
	StreetBet int64                  `json:"streetBet"`

	// TimeBankMs The actor's time bank left after this action.
	TimeBankMs *int64 `json:"timeBankMs,omitempty"`
	Timeout    bool   `json:"timeout"`
}

// PlayerActedEventAction defines model for PlayerActedEvent.Action.
type PlayerActedEventAction string

// PlayerActedEventKind defines model for PlayerActedEvent.Kind.
type PlayerActedEventKind string

// PlayerLeftEvent defines model for PlayerLeftEvent.
type PlayerLeftEvent struct {
	CashOut int64               `json:"cashOut"`
	Kind    PlayerLeftEventKind `json:"kind"`
	Place   *int                `json:"place,omitempty"`

	// Reason Tournaments: MOVED (balancing; see toTableId), ELIMINATED (with the
	// finishing place) and FINISHED (the tournament ended; the winner's
	// place is 1).
	Reason PlayerLeftEventReason `json:"reason"`

	// Seat 0 for a tournament player redirected before taking a seat here (reason MOVED).
	Seat      int                 `json:"seat"`
	ToTableId *openapi_types.UUID `json:"toTableId,omitempty"`
	UserId    openapi_types.UUID  `json:"userId"`
}

// PlayerLeftEventKind defines model for PlayerLeftEvent.Kind.
type PlayerLeftEventKind string

// PlayerLeftEventReason Tournaments: MOVED (balancing; see toTableId), ELIMINATED (with the
// finishing place) and FINISHED (the tournament ended; the winner's
// place is 1).
type PlayerLeftEventReason string

// PlayerSeatedEvent defines model for PlayerSeatedEvent.
type PlayerSeatedEvent struct {
	Kind     PlayerSeatedEventKind `json:"kind"`
	Seat     int                   `json:"seat"`
	Stack    int64                 `json:"stack"`
	UserId   openapi_types.UUID    `json:"userId"`
	Username string                `json:"username"`
}

// PlayerSeatedEventKind defines model for PlayerSeatedEvent.Kind.
type PlayerSeatedEventKind string

// PlayerSittingOutEvent defines model for PlayerSittingOutEvent.
type PlayerSittingOutEvent struct {
	Kind PlayerSittingOutEventKind `json:"kind"`

	// Reason BUSTED - out of chips, the seat is kept until `until` for a re-buy; TOP_UP - back in after a re-buy.
	Reason     *PlayerSittingOutEventReason `json:"reason,omitempty"`
	Seat       int                          `json:"seat"`
	SittingOut bool                         `json:"sittingOut"`

	// Until With BUSTED, when the seat is released unless the player re-buys.
	Until  *time.Time         `json:"until,omitempty"`
	UserId openapi_types.UUID `json:"userId"`
}

// PlayerSittingOutEventKind defines model for PlayerSittingOutEvent.Kind.
type PlayerSittingOutEventKind string

// PlayerSittingOutEventReason BUSTED - out of chips, the seat is kept until `until` for a re-buy; TOP_UP - back in after a re-buy.
type PlayerSittingOutEventReason string

// PlayerToppedUpEvent defines model for PlayerToppedUpEvent.
type PlayerToppedUpEvent struct {
	// Amount Chips added from the club wallet (a re-buy when the stack was empty).
	Amount int64                   `json:"amount"`
	Kind   PlayerToppedUpEventKind `json:"kind"`
	Seat   int                     `json:"seat"`
	Stack  int64                   `json:"stack"`
	UserId openapi_types.UUID      `json:"userId"`
}

// PlayerToppedUpEventKind defines model for PlayerToppedUpEvent.Kind.
type PlayerToppedUpEventKind string

// Pong defines model for Pong.
type Pong struct {
	Nonce *string  `json:"nonce,omitempty"`
	Type  PongType `json:"type"`
}

// PongType defines model for Pong.Type.
type PongType string

// PotAwardedEvent defines model for PotAwardedEvent.
type PotAwardedEvent struct {
	Amount        int64               `json:"amount"`
	Description   string              `json:"description"`
	EligibleSeats []int               `json:"eligibleSeats"`
	Kind          PotAwardedEventKind `json:"kind"`
	PotIndex      int                 `json:"potIndex"`
	Winners       []WinnerShare       `json:"winners"`
}

// PotAwardedEventKind defines model for PotAwardedEvent.Kind.
type PotAwardedEventKind string

// ProtocolError Connection- or subscription-level error (not tied to a table command).
type ProtocolError struct {
	// Code An ErrorCode value from the control-api contract.
	Code      string              `json:"code"`
	Message   string              `json:"message"`
	RequestId *string             `json:"requestId,omitempty"`
	TableId   *openapi_types.UUID `json:"tableId,omitempty"`
	Type      ProtocolErrorType   `json:"type"`
}

// ProtocolErrorType defines model for ProtocolError.Type.
type ProtocolErrorType string

// ResyncRequired The client fell outside the retained event window; a TABLE_SNAPSHOT follows.
type ResyncRequired struct {
	CurrentSeq int64                `json:"currentSeq"`
	Reason     ResyncRequiredReason `json:"reason"`
	TableId    openapi_types.UUID   `json:"tableId"`
	Type       ResyncRequiredType   `json:"type"`
}

// ResyncRequiredReason defines model for ResyncRequired.Reason.
type ResyncRequiredReason string

// ResyncRequiredType defines model for ResyncRequired.Type.
type ResyncRequiredType string

// SeatView defines model for SeatView.
type SeatView struct {
	AllIn bool `json:"allIn"`

	// BustedUntil Set while the player is out of chips; the seat is released at this time unless they re-buy.
	BustedUntil *time.Time `json:"bustedUntil,omitempty"`
	Folded      bool       `json:"folded"`
	InHand      bool       `json:"inHand"`
	Leaving     bool       `json:"leaving"`
	Seat        int        `json:"seat"`

	// ShownCards Cards revealed at showdown (public).
	ShownCards *[]Card `json:"shownCards,omitempty"`
	SittingOut bool    `json:"sittingOut"`
	Stack      int64   `json:"stack"`
	StreetBet  int64   `json:"streetBet"`

	// TimeBankMs Time bank left (while it runs, the value from before it started).
	TimeBankMs int64              `json:"timeBankMs"`
	UserId     openapi_types.UUID `json:"userId"`
	Username   string             `json:"username"`
}

// ServerMessageType defines model for ServerMessageType.
type ServerMessageType string

// StreetDealtEvent defines model for StreetDealtEvent.
type StreetDealtEvent struct {
	Board  []Card                 `json:"board"`
	Cards  []Card                 `json:"cards"`
	Kind   StreetDealtEventKind   `json:"kind"`
	Street StreetDealtEventStreet `json:"street"`
}

// StreetDealtEventKind defines model for StreetDealtEvent.Kind.
type StreetDealtEventKind string

// StreetDealtEventStreet defines model for StreetDealtEvent.Street.
type StreetDealtEventStreet string

// SubscribeTable Subscribe to a table. With lastSeenSeq the server replays missed
// events if they are retained, otherwise it sends RESYNC_REQUIRED and a
// fresh TABLE_SNAPSHOT. Without lastSeenSeq a TABLE_SNAPSHOT is sent.
type SubscribeTable struct {
	LastSeenSeq *int64             `json:"lastSeenSeq,omitempty"`
	RequestId   *string            `json:"requestId,omitempty"`
	TableId     openapi_types.UUID `json:"tableId"`
	Type        SubscribeTableType `json:"type"`
}

// SubscribeTableType defines model for SubscribeTable.Type.
type SubscribeTableType string

// Subscribed Subscription is live; `replayed` events were sent before it (REPLAY mode).
type Subscribed struct {
	Mode      SubscribedMode     `json:"mode"`
	Replayed  int                `json:"replayed"`
	RequestId *string            `json:"requestId,omitempty"`
	Seq       int64              `json:"seq"`
	TableId   openapi_types.UUID `json:"tableId"`
	Type      SubscribedType     `json:"type"`
}

// SubscribedMode defines model for Subscribed.Mode.
type SubscribedMode string

// SubscribedType defines model for Subscribed.Type.
type SubscribedType string

// TableClosedEvent The table accepts no new hands or players. Seated players are cashed
// out to their club wallets (PLAYER_LEFT reason TABLE_CLOSED) as soon as
// no hand is in progress.
type TableClosedEvent struct {
	Kind TableClosedEventKind `json:"kind"`
}

// TableClosedEventKind defines model for TableClosedEvent.Kind.
type TableClosedEventKind string

// TableEventMessage defines model for TableEventMessage.
type TableEventMessage struct {
	// Event Ordered table event (discriminated by kind). Private fields only appear in the recipient's copy.
	Event      TableEventPayload     `json:"event"`
	HandId     *openapi_types.UUID   `json:"handId,omitempty"`
	Seq        int64                 `json:"seq"`
	ServerTime time.Time             `json:"serverTime"`
	TableId    openapi_types.UUID    `json:"tableId"`
	Type       TableEventMessageType `json:"type"`
}

// TableEventMessageType defines model for TableEventMessage.Type.
type TableEventMessageType string

// TableEventPayload Ordered table event (discriminated by kind). Private fields only appear in the recipient's copy.
type TableEventPayload struct {
	union json.RawMessage
}

// TableInfo defines model for TableInfo.
type TableInfo struct {
	ActionTimeoutMs int64              `json:"actionTimeoutMs"`
	BigBlind        int64              `json:"bigBlind"`
	BuyInMax        int64              `json:"buyInMax"`
	BuyInMin        int64              `json:"buyInMin"`
	ClubId          openapi_types.UUID `json:"clubId"`

	// GameType NLHE = No-Limit Texas Hold'em (2 hole cards). PLO = Pot-Limit Omaha
	// (4 hole cards; a hand uses exactly two of them and three board cards;
	// bets and raises are capped at the pot).
	GameType   GameType        `json:"gameType"`
	MaxSeats   int             `json:"maxSeats"`
	Name       string          `json:"name"`
	SmallBlind int64           `json:"smallBlind"`
	Status     TableInfoStatus `json:"status"`

	// TimeBankMs Each seat's time bank (also its cap); 0 when the table has none.
	TimeBankMs int64 `json:"timeBankMs"`

	// TimeBankRefillMs Added back for every hand a player is dealt into, up to timeBankMs.
	TimeBankRefillMs int64 `json:"timeBankRefillMs"`

	// Tournament Tournament context of a tournament table (level and blinds in effect for new hands).
	Tournament *TournamentTableInfo `json:"tournament,omitempty"`
}

// TableInfoStatus defines model for TableInfo.Status.
type TableInfoStatus string

// TableSnapshot Complete viewer-sanitized table state; clients replace (never merge) state with it.
type TableSnapshot struct {
	// Hand Present while a hand is in progress or just completed.
	Hand       *HandView          `json:"hand,omitempty"`
	Phase      TableSnapshotPhase `json:"phase"`
	Seats      []SeatView         `json:"seats"`
	Seq        int64              `json:"seq"`
	ServerTime time.Time          `json:"serverTime"`
	Table      TableInfo          `json:"table"`
	TableId    openapi_types.UUID `json:"tableId"`

	// You The viewer's private view (absent for anonymous spectators).
	You *YouView `json:"you,omitempty"`
}

// TableSnapshotPhase defines model for TableSnapshot.Phase.
type TableSnapshotPhase string

// TableSnapshotMessage defines model for TableSnapshotMessage.
type TableSnapshotMessage struct {
	Seq int64 `json:"seq"`

	// Snapshot Complete viewer-sanitized table state; clients replace (never merge) state with it.
	Snapshot TableSnapshot            `json:"snapshot"`
	TableId  openapi_types.UUID       `json:"tableId"`
	Type     TableSnapshotMessageType `json:"type"`
}

// TableSnapshotMessageType defines model for TableSnapshotMessage.Type.
type TableSnapshotMessageType string

// TimeBankStartedEvent The actor's turn timer ran out and their time bank is running; deadline replaces the turn's.
type TimeBankStartedEvent struct {
	Deadline time.Time                `json:"deadline"`
	Kind     TimeBankStartedEventKind `json:"kind"`
	Seat     int                      `json:"seat"`

	// TimeoutMs Length of the time bank now running (all that was left).
	TimeoutMs int64 `json:"timeoutMs"`
}

// TimeBankStartedEventKind defines model for TimeBankStartedEvent.Kind.
type TimeBankStartedEventKind string

// TournamentTableInfo Tournament context of a tournament table (level and blinds in effect for new hands).
type TournamentTableInfo struct {
	BigBlind       int64                     `json:"bigBlind"`
	Level          int                       `json:"level"`
	LevelEndsAt    time.Time                 `json:"levelEndsAt"`
	Name           string                    `json:"name"`
	NextBigBlind   int64                     `json:"nextBigBlind"`
	NextSmallBlind int64                     `json:"nextSmallBlind"`
	SmallBlind     int64                     `json:"smallBlind"`
	Status         TournamentTableInfoStatus `json:"status"`
	TableNo        int                       `json:"tableNo"`
	TournamentId   openapi_types.UUID        `json:"tournamentId"`
}

// TournamentTableInfoStatus defines model for TournamentTableInfo.Status.
type TournamentTableInfoStatus string

// TurnStartedEvent defines model for TurnStartedEvent.
type TurnStartedEvent struct {
	CurrentBet int64                `json:"currentBet"`
	Deadline   time.Time            `json:"deadline"`
	Kind       TurnStartedEventKind `json:"kind"`

	// LegalActions Private to the acting player.
	LegalActions *[]LegalAction         `json:"legalActions,omitempty"`
	MinRaise     int64                  `json:"minRaise"`
	Pot          int64                  `json:"pot"`
	Seat         int                    `json:"seat"`
	Street       TurnStartedEventStreet `json:"street"`

	// TimeBankMs The actor's time bank, used if the turn timer runs out.
	TimeBankMs int64 `json:"timeBankMs"`
	TimeoutMs  int64 `json:"timeoutMs"`
}

// TurnStartedEventKind defines model for TurnStartedEvent.Kind.
type TurnStartedEventKind string

// TurnStartedEventStreet defines model for TurnStartedEvent.Street.
type TurnStartedEventStreet string

// UncalledBetReturnedEvent defines model for UncalledBetReturnedEvent.
type UncalledBetReturnedEvent struct {
	Amount int64                        `json:"amount"`
	Kind   UncalledBetReturnedEventKind `json:"kind"`
	Pot    int64                        `json:"pot"`
	Seat   int                          `json:"seat"`
	Stack  int64                        `json:"stack"`
}

// UncalledBetReturnedEventKind defines model for UncalledBetReturnedEvent.Kind.
type UncalledBetReturnedEventKind string

// UnsubscribeTable defines model for UnsubscribeTable.
type UnsubscribeTable struct {
	TableId openapi_types.UUID   `json:"tableId"`
	Type    UnsubscribeTableType `json:"type"`
}

// UnsubscribeTableType defines model for UnsubscribeTable.Type.
type UnsubscribeTableType string

// Welcome defines model for Welcome.
type Welcome struct {
	ConnectionId        string             `json:"connectionId"`
	HeartbeatIntervalMs int                `json:"heartbeatIntervalMs"`
	ServerTime          time.Time          `json:"serverTime"`
	TokenExpiresAt      time.Time          `json:"tokenExpiresAt"`
	Type                WelcomeType        `json:"type"`
	UserId              openapi_types.UUID `json:"userId"`
}

// WelcomeType defines model for Welcome.Type.
type WelcomeType string

// WinnerShare defines model for WinnerShare.
type WinnerShare struct {
	Amount int64 `json:"amount"`
	Seat   int   `json:"seat"`
}

// YouView defines model for YouView.
type YouView struct {
	// AutoTopUpTo The viewer's automatic top-up target (0 = off).
	AutoTopUpTo  int64         `json:"autoTopUpTo"`
	HoleCards    []Card        `json:"holeCards"`
	LegalActions []LegalAction `json:"legalActions"`

	// PendingTopUp Chips the viewer added during the current hand, applied when it ends.
	PendingTopUp int64 `json:"pendingTopUp"`

	// Seat 0 when the viewer is not seated.
	Seat   int                `json:"seat"`
	UserId openapi_types.UUID `json:"userId"`
}

// AsPlayerSeatedEvent returns the union data inside the TableEventPayload as a PlayerSeatedEvent
func (t TableEventPayload) AsPlayerSeatedEvent() (PlayerSeatedEvent, error) {
	var body PlayerSeatedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPlayerSeatedEvent overwrites any union data inside the TableEventPayload as the provided PlayerSeatedEvent
func (t *TableEventPayload) FromPlayerSeatedEvent(v PlayerSeatedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"PLAYER_SEATED"}`))
	t.union = b
	return err
}

// MergePlayerSeatedEvent performs a merge with any union data inside the TableEventPayload, using the provided PlayerSeatedEvent
func (t *TableEventPayload) MergePlayerSeatedEvent(v PlayerSeatedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"PLAYER_SEATED"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPlayerLeftEvent returns the union data inside the TableEventPayload as a PlayerLeftEvent
func (t TableEventPayload) AsPlayerLeftEvent() (PlayerLeftEvent, error) {
	var body PlayerLeftEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPlayerLeftEvent overwrites any union data inside the TableEventPayload as the provided PlayerLeftEvent
func (t *TableEventPayload) FromPlayerLeftEvent(v PlayerLeftEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"PLAYER_LEFT"}`))
	t.union = b
	return err
}

// MergePlayerLeftEvent performs a merge with any union data inside the TableEventPayload, using the provided PlayerLeftEvent
func (t *TableEventPayload) MergePlayerLeftEvent(v PlayerLeftEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"PLAYER_LEFT"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPlayerSittingOutEvent returns the union data inside the TableEventPayload as a PlayerSittingOutEvent
func (t TableEventPayload) AsPlayerSittingOutEvent() (PlayerSittingOutEvent, error) {
	var body PlayerSittingOutEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPlayerSittingOutEvent overwrites any union data inside the TableEventPayload as the provided PlayerSittingOutEvent
func (t *TableEventPayload) FromPlayerSittingOutEvent(v PlayerSittingOutEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"PLAYER_SITTING_OUT"}`))
	t.union = b
	return err
}

// MergePlayerSittingOutEvent performs a merge with any union data inside the TableEventPayload, using the provided PlayerSittingOutEvent
func (t *TableEventPayload) MergePlayerSittingOutEvent(v PlayerSittingOutEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"PLAYER_SITTING_OUT"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPlayerToppedUpEvent returns the union data inside the TableEventPayload as a PlayerToppedUpEvent
func (t TableEventPayload) AsPlayerToppedUpEvent() (PlayerToppedUpEvent, error) {
	var body PlayerToppedUpEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPlayerToppedUpEvent overwrites any union data inside the TableEventPayload as the provided PlayerToppedUpEvent
func (t *TableEventPayload) FromPlayerToppedUpEvent(v PlayerToppedUpEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"PLAYER_TOPPED_UP"}`))
	t.union = b
	return err
}

// MergePlayerToppedUpEvent performs a merge with any union data inside the TableEventPayload, using the provided PlayerToppedUpEvent
func (t *TableEventPayload) MergePlayerToppedUpEvent(v PlayerToppedUpEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"PLAYER_TOPPED_UP"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsHandStartedEvent returns the union data inside the TableEventPayload as a HandStartedEvent
func (t TableEventPayload) AsHandStartedEvent() (HandStartedEvent, error) {
	var body HandStartedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHandStartedEvent overwrites any union data inside the TableEventPayload as the provided HandStartedEvent
func (t *TableEventPayload) FromHandStartedEvent(v HandStartedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"HAND_STARTED"}`))
	t.union = b
	return err
}

// MergeHandStartedEvent performs a merge with any union data inside the TableEventPayload, using the provided HandStartedEvent
func (t *TableEventPayload) MergeHandStartedEvent(v HandStartedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"HAND_STARTED"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBlindPostedEvent returns the union data inside the TableEventPayload as a BlindPostedEvent
func (t TableEventPayload) AsBlindPostedEvent() (BlindPostedEvent, error) {
	var body BlindPostedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBlindPostedEvent overwrites any union data inside the TableEventPayload as the provided BlindPostedEvent
func (t *TableEventPayload) FromBlindPostedEvent(v BlindPostedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"BLIND_POSTED"}`))
	t.union = b
	return err
}

// MergeBlindPostedEvent performs a merge with any union data inside the TableEventPayload, using the provided BlindPostedEvent
func (t *TableEventPayload) MergeBlindPostedEvent(v BlindPostedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"BLIND_POSTED"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsHoleCardsDealtEvent returns the union data inside the TableEventPayload as a HoleCardsDealtEvent
func (t TableEventPayload) AsHoleCardsDealtEvent() (HoleCardsDealtEvent, error) {
	var body HoleCardsDealtEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHoleCardsDealtEvent overwrites any union data inside the TableEventPayload as the provided HoleCardsDealtEvent
func (t *TableEventPayload) FromHoleCardsDealtEvent(v HoleCardsDealtEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"HOLE_CARDS_DEALT"}`))
	t.union = b
	return err
}

// MergeHoleCardsDealtEvent performs a merge with any union data inside the TableEventPayload, using the provided HoleCardsDealtEvent
func (t *TableEventPayload) MergeHoleCardsDealtEvent(v HoleCardsDealtEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"HOLE_CARDS_DEALT"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPlayerActedEvent returns the union data inside the TableEventPayload as a PlayerActedEvent
func (t TableEventPayload) AsPlayerActedEvent() (PlayerActedEvent, error) {
	var body PlayerActedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPlayerActedEvent overwrites any union data inside the TableEventPayload as the provided PlayerActedEvent
func (t *TableEventPayload) FromPlayerActedEvent(v PlayerActedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"PLAYER_ACTED"}`))
	t.union = b
	return err
}

// MergePlayerActedEvent performs a merge with any union data inside the TableEventPayload, using the provided PlayerActedEvent
func (t *TableEventPayload) MergePlayerActedEvent(v PlayerActedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"PLAYER_ACTED"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTurnStartedEvent returns the union data inside the TableEventPayload as a TurnStartedEvent
func (t TableEventPayload) AsTurnStartedEvent() (TurnStartedEvent, error) {
	var body TurnStartedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTurnStartedEvent overwrites any union data inside the TableEventPayload as the provided TurnStartedEvent
func (t *TableEventPayload) FromTurnStartedEvent(v TurnStartedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"TURN_STARTED"}`))
	t.union = b
	return err
}

// MergeTurnStartedEvent performs a merge with any union data inside the TableEventPayload, using the provided TurnStartedEvent
func (t *TableEventPayload) MergeTurnStartedEvent(v TurnStartedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"TURN_STARTED"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTimeBankStartedEvent returns the union data inside the TableEventPayload as a TimeBankStartedEvent
func (t TableEventPayload) AsTimeBankStartedEvent() (TimeBankStartedEvent, error) {
	var body TimeBankStartedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTimeBankStartedEvent overwrites any union data inside the TableEventPayload as the provided TimeBankStartedEvent
func (t *TableEventPayload) FromTimeBankStartedEvent(v TimeBankStartedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"TIME_BANK_STARTED"}`))
	t.union = b
	return err
}

// MergeTimeBankStartedEvent performs a merge with any union data inside the TableEventPayload, using the provided TimeBankStartedEvent
func (t *TableEventPayload) MergeTimeBankStartedEvent(v TimeBankStartedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"TIME_BANK_STARTED"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUncalledBetReturnedEvent returns the union data inside the TableEventPayload as a UncalledBetReturnedEvent
func (t TableEventPayload) AsUncalledBetReturnedEvent() (UncalledBetReturnedEvent, error) {
	var body UncalledBetReturnedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUncalledBetReturnedEvent overwrites any union data inside the TableEventPayload as the provided UncalledBetReturnedEvent
func (t *TableEventPayload) FromUncalledBetReturnedEvent(v UncalledBetReturnedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"UNCALLED_BET_RETURNED"}`))
	t.union = b
	return err
}

// MergeUncalledBetReturnedEvent performs a merge with any union data inside the TableEventPayload, using the provided UncalledBetReturnedEvent
func (t *TableEventPayload) MergeUncalledBetReturnedEvent(v UncalledBetReturnedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"UNCALLED_BET_RETURNED"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStreetDealtEvent returns the union data inside the TableEventPayload as a StreetDealtEvent
func (t TableEventPayload) AsStreetDealtEvent() (StreetDealtEvent, error) {
	var body StreetDealtEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStreetDealtEvent overwrites any union data inside the TableEventPayload as the provided StreetDealtEvent
func (t *TableEventPayload) FromStreetDealtEvent(v StreetDealtEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"STREET_DEALT"}`))
	t.union = b
	return err
}

// MergeStreetDealtEvent performs a merge with any union data inside the TableEventPayload, using the provided StreetDealtEvent
func (t *TableEventPayload) MergeStreetDealtEvent(v StreetDealtEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"STREET_DEALT"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCardsRevealedEvent returns the union data inside the TableEventPayload as a CardsRevealedEvent
func (t TableEventPayload) AsCardsRevealedEvent() (CardsRevealedEvent, error) {
	var body CardsRevealedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCardsRevealedEvent overwrites any union data inside the TableEventPayload as the provided CardsRevealedEvent
func (t *TableEventPayload) FromCardsRevealedEvent(v CardsRevealedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"CARDS_REVEALED"}`))
	t.union = b
	return err
}

// MergeCardsRevealedEvent performs a merge with any union data inside the TableEventPayload, using the provided CardsRevealedEvent
func (t *TableEventPayload) MergeCardsRevealedEvent(v CardsRevealedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"CARDS_REVEALED"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPotAwardedEvent returns the union data inside the TableEventPayload as a PotAwardedEvent
func (t TableEventPayload) AsPotAwardedEvent() (PotAwardedEvent, error) {
	var body PotAwardedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPotAwardedEvent overwrites any union data inside the TableEventPayload as the provided PotAwardedEvent
func (t *TableEventPayload) FromPotAwardedEvent(v PotAwardedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"POT_AWARDED"}`))
	t.union = b
	return err
}

// MergePotAwardedEvent performs a merge with any union data inside the TableEventPayload, using the provided PotAwardedEvent
func (t *TableEventPayload) MergePotAwardedEvent(v PotAwardedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"POT_AWARDED"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsHandCompletedEvent returns the union data inside the TableEventPayload as a HandCompletedEvent
func (t TableEventPayload) AsHandCompletedEvent() (HandCompletedEvent, error) {
	var body HandCompletedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHandCompletedEvent overwrites any union data inside the TableEventPayload as the provided HandCompletedEvent
func (t *TableEventPayload) FromHandCompletedEvent(v HandCompletedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"HAND_COMPLETED"}`))
	t.union = b
	return err
}

// MergeHandCompletedEvent performs a merge with any union data inside the TableEventPayload, using the provided HandCompletedEvent
func (t *TableEventPayload) MergeHandCompletedEvent(v HandCompletedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"HAND_COMPLETED"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsHandVoidedEvent returns the union data inside the TableEventPayload as a HandVoidedEvent
func (t TableEventPayload) AsHandVoidedEvent() (HandVoidedEvent, error) {
	var body HandVoidedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHandVoidedEvent overwrites any union data inside the TableEventPayload as the provided HandVoidedEvent
func (t *TableEventPayload) FromHandVoidedEvent(v HandVoidedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"HAND_VOIDED"}`))
	t.union = b
	return err
}

// MergeHandVoidedEvent performs a merge with any union data inside the TableEventPayload, using the provided HandVoidedEvent
func (t *TableEventPayload) MergeHandVoidedEvent(v HandVoidedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"HAND_VOIDED"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTableClosedEvent returns the union data inside the TableEventPayload as a TableClosedEvent
func (t TableEventPayload) AsTableClosedEvent() (TableClosedEvent, error) {
	var body TableClosedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTableClosedEvent overwrites any union data inside the TableEventPayload as the provided TableClosedEvent
func (t *TableEventPayload) FromTableClosedEvent(v TableClosedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"TABLE_CLOSED"}`))
	t.union = b
	return err
}

// MergeTableClosedEvent performs a merge with any union data inside the TableEventPayload, using the provided TableClosedEvent
func (t *TableEventPayload) MergeTableClosedEvent(v TableClosedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"TABLE_CLOSED"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TableEventPayload) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t TableEventPayload) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "BLIND_POSTED":
		return t.AsBlindPostedEvent()
	case "CARDS_REVEALED":
		return t.AsCardsRevealedEvent()
	case "HAND_COMPLETED":
		return t.AsHandCompletedEvent()
	case "HAND_STARTED":
		return t.AsHandStartedEvent()
	case "HAND_VOIDED":
		return t.AsHandVoidedEvent()
	case "HOLE_CARDS_DEALT":
		return t.AsHoleCardsDealtEvent()
	case "PLAYER_ACTED":
		return t.AsPlayerActedEvent()
	case "PLAYER_LEFT":
		return t.AsPlayerLeftEvent()
	case "PLAYER_SEATED":
		return t.AsPlayerSeatedEvent()
	case "PLAYER_SITTING_OUT":
		return t.AsPlayerSittingOutEvent()
	case "PLAYER_TOPPED_UP":
		return t.AsPlayerToppedUpEvent()
	case "POT_AWARDED":
		return t.AsPotAwardedEvent()
	case "STREET_DEALT":
		return t.AsStreetDealtEvent()
	case "TABLE_CLOSED":
		return t.AsTableClosedEvent()
	case "TIME_BANK_STARTED":
		return t.AsTimeBankStartedEvent()
	case "TURN_STARTED":
		return t.AsTurnStartedEvent()
	case "UNCALLED_BET_RETURNED":
		return t.AsUncalledBetReturnedEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t TableEventPayload) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TableEventPayload) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
