// Package realtime provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package realtime

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ClientMessageType.
const (
	ClientMessageTypeCOMMAND          ClientMessageType = "COMMAND"
	ClientMessageTypeHELLO            ClientMessageType = "HELLO"
	ClientMessageTypePING             ClientMessageType = "PING"
	ClientMessageTypePONG             ClientMessageType = "PONG"
	ClientMessageTypeSUBSCRIBETABLE   ClientMessageType = "SUBSCRIBE_TABLE"
	ClientMessageTypeUNSUBSCRIBETABLE ClientMessageType = "UNSUBSCRIBE_TABLE"
)

// Valid indicates whether the value is a known member of the ClientMessageType enum.
func (e ClientMessageType) Valid() bool {
	switch e {
	case ClientMessageTypeCOMMAND:
		return true
	case ClientMessageTypeHELLO:
		return true
	case ClientMessageTypePING:
		return true
	case ClientMessageTypePONG:
		return true
	case ClientMessageTypeSUBSCRIBETABLE:
		return true
	case ClientMessageTypeUNSUBSCRIBETABLE:
		return true
	default:
		return false
	}
}

// Defines values for HelloType.
const (
	HelloTypeHELLO HelloType = "HELLO"
)

// Valid indicates whether the value is a known member of the HelloType enum.
func (e HelloType) Valid() bool {
	switch e {
	case HelloTypeHELLO:
		return true
	default:
		return false
	}
}

// Defines values for PingType.
const (
	PingTypePING PingType = "PING"
)

// Valid indicates whether the value is a known member of the PingType enum.
func (e PingType) Valid() bool {
	switch e {
	case PingTypePING:
		return true
	default:
		return false
	}
}

// Defines values for PongType.
const (
	PongTypePONG PongType = "PONG"
)

// Valid indicates whether the value is a known member of the PongType enum.
func (e PongType) Valid() bool {
	switch e {
	case PongTypePONG:
		return true
	default:
		return false
	}
}

// Defines values for ProtocolErrorType.
const (
	ProtocolErrorTypeERROR ProtocolErrorType = "ERROR"
)

// Valid indicates whether the value is a known member of the ProtocolErrorType enum.
func (e ProtocolErrorType) Valid() bool {
	switch e {
	case ProtocolErrorTypeERROR:
		return true
	default:
		return false
	}
}

// Defines values for ServerMessageType.
const (
	ServerMessageTypeCOMMANDRESULT  ServerMessageType = "COMMAND_RESULT"
	ServerMessageTypeERROR          ServerMessageType = "ERROR"
	ServerMessageTypePING           ServerMessageType = "PING"
	ServerMessageTypePONG           ServerMessageType = "PONG"
	ServerMessageTypeRESYNCREQUIRED ServerMessageType = "RESYNC_REQUIRED"
	ServerMessageTypeTABLEEVENT     ServerMessageType = "TABLE_EVENT"
	ServerMessageTypeTABLESNAPSHOT  ServerMessageType = "TABLE_SNAPSHOT"
	ServerMessageTypeWELCOME        ServerMessageType = "WELCOME"
)

// Valid indicates whether the value is a known member of the ServerMessageType enum.
func (e ServerMessageType) Valid() bool {
	switch e {
	case ServerMessageTypeCOMMANDRESULT:
		return true
	case ServerMessageTypeERROR:
		return true
	case ServerMessageTypePING:
		return true
	case ServerMessageTypePONG:
		return true
	case ServerMessageTypeRESYNCREQUIRED:
		return true
	case ServerMessageTypeTABLEEVENT:
		return true
	case ServerMessageTypeTABLESNAPSHOT:
		return true
	case ServerMessageTypeWELCOME:
		return true
	default:
		return false
	}
}

// Defines values for WelcomeType.
const (
	WelcomeTypeWELCOME WelcomeType = "WELCOME"
)

// Valid indicates whether the value is a known member of the WelcomeType enum.
func (e WelcomeType) Valid() bool {
	switch e {
	case WelcomeTypeWELCOME:
		return true
	default:
		return false
	}
}

// ClientMessageType defines model for ClientMessageType.
type ClientMessageType string

// Hello First client frame. Authenticates the connection.
type Hello struct {
	AccessToken   string    `json:"accessToken"`
	ClientVersion string    `json:"clientVersion"`
	DeviceId      *string   `json:"deviceId,omitempty"`
	Type          HelloType `json:"type"`
}

// HelloType defines model for Hello.Type.
type HelloType string

// Ping defines model for Ping.
type Ping struct {
	Nonce *string  `json:"nonce,omitempty"`
	Type  PingType `json:"type"`
}

// PingType defines model for Ping.Type.
type PingType string

// Pong defines model for Pong.
type Pong struct {
	Nonce *string  `json:"nonce,omitempty"`
	Type  PongType `json:"type"`
}

// PongType defines model for Pong.Type.
type PongType string

// ProtocolError Connection-level error (not tied to a table command).
type ProtocolError struct {
	// Code An ErrorCode value from the control-api contract.
	Code      string              `json:"code"`
	Message   string              `json:"message"`
	RequestId *string             `json:"requestId,omitempty"`
	TableId   *openapi_types.UUID `json:"tableId,omitempty"`
	Type      ProtocolErrorType   `json:"type"`
}

// ProtocolErrorType defines model for ProtocolError.Type.
type ProtocolErrorType string

// ServerMessageType defines model for ServerMessageType.
type ServerMessageType string

// Welcome defines model for Welcome.
type Welcome struct {
	ConnectionId        string             `json:"connectionId"`
	HeartbeatIntervalMs int                `json:"heartbeatIntervalMs"`
	ServerTime          time.Time          `json:"serverTime"`
	Type                WelcomeType        `json:"type"`
	UserId              openapi_types.UUID `json:"userId"`
}

// WelcomeType defines model for Welcome.Type.
type WelcomeType string
