// Package realtime provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package realtime

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ClientMessageType.
const (
	ClientMessageTypeCOMMAND          ClientMessageType = "COMMAND"
	ClientMessageTypeHELLO            ClientMessageType = "HELLO"
	ClientMessageTypePING             ClientMessageType = "PING"
	ClientMessageTypePONG             ClientMessageType = "PONG"
	ClientMessageTypeSUBSCRIBETABLE   ClientMessageType = "SUBSCRIBE_TABLE"
	ClientMessageTypeUNSUBSCRIBETABLE ClientMessageType = "UNSUBSCRIBE_TABLE"
)

// Valid indicates whether the value is a known member of the ClientMessageType enum.
func (e ClientMessageType) Valid() bool {
	switch e {
	case ClientMessageTypeCOMMAND:
		return true
	case ClientMessageTypeHELLO:
		return true
	case ClientMessageTypePING:
		return true
	case ClientMessageTypePONG:
		return true
	case ClientMessageTypeSUBSCRIBETABLE:
		return true
	case ClientMessageTypeUNSUBSCRIBETABLE:
		return true
	default:
		return false
	}
}

// Defines values for HandViewStreet.
const (
	HandViewStreetCOMPLETE HandViewStreet = "COMPLETE"
	HandViewStreetFLOP     HandViewStreet = "FLOP"
	HandViewStreetPREFLOP  HandViewStreet = "PREFLOP"
	HandViewStreetRIVER    HandViewStreet = "RIVER"
	HandViewStreetSHOWDOWN HandViewStreet = "SHOWDOWN"
	HandViewStreetTURN     HandViewStreet = "TURN"
)

// Valid indicates whether the value is a known member of the HandViewStreet enum.
func (e HandViewStreet) Valid() bool {
	switch e {
	case HandViewStreetCOMPLETE:
		return true
	case HandViewStreetFLOP:
		return true
	case HandViewStreetPREFLOP:
		return true
	case HandViewStreetRIVER:
		return true
	case HandViewStreetSHOWDOWN:
		return true
	case HandViewStreetTURN:
		return true
	default:
		return false
	}
}

// Defines values for HelloType.
const (
	HelloTypeHELLO HelloType = "HELLO"
)

// Valid indicates whether the value is a known member of the HelloType enum.
func (e HelloType) Valid() bool {
	switch e {
	case HelloTypeHELLO:
		return true
	default:
		return false
	}
}

// Defines values for LegalActionKind.
const (
	LegalActionKindALLIN LegalActionKind = "ALL_IN"
	LegalActionKindBET   LegalActionKind = "BET"
	LegalActionKindCALL  LegalActionKind = "CALL"
	LegalActionKindCHECK LegalActionKind = "CHECK"
	LegalActionKindFOLD  LegalActionKind = "FOLD"
	LegalActionKindRAISE LegalActionKind = "RAISE"
)

// Valid indicates whether the value is a known member of the LegalActionKind enum.
func (e LegalActionKind) Valid() bool {
	switch e {
	case LegalActionKindALLIN:
		return true
	case LegalActionKindBET:
		return true
	case LegalActionKindCALL:
		return true
	case LegalActionKindCHECK:
		return true
	case LegalActionKindFOLD:
		return true
	case LegalActionKindRAISE:
		return true
	default:
		return false
	}
}

// Defines values for PingType.
const (
	PingTypePING PingType = "PING"
)

// Valid indicates whether the value is a known member of the PingType enum.
func (e PingType) Valid() bool {
	switch e {
	case PingTypePING:
		return true
	default:
		return false
	}
}

// Defines values for PongType.
const (
	PongTypePONG PongType = "PONG"
)

// Valid indicates whether the value is a known member of the PongType enum.
func (e PongType) Valid() bool {
	switch e {
	case PongTypePONG:
		return true
	default:
		return false
	}
}

// Defines values for ProtocolErrorType.
const (
	ProtocolErrorTypeERROR ProtocolErrorType = "ERROR"
)

// Valid indicates whether the value is a known member of the ProtocolErrorType enum.
func (e ProtocolErrorType) Valid() bool {
	switch e {
	case ProtocolErrorTypeERROR:
		return true
	default:
		return false
	}
}

// Defines values for ServerMessageType.
const (
	ServerMessageTypeCOMMANDRESULT  ServerMessageType = "COMMAND_RESULT"
	ServerMessageTypeERROR          ServerMessageType = "ERROR"
	ServerMessageTypePING           ServerMessageType = "PING"
	ServerMessageTypePONG           ServerMessageType = "PONG"
	ServerMessageTypeRESYNCREQUIRED ServerMessageType = "RESYNC_REQUIRED"
	ServerMessageTypeTABLEEVENT     ServerMessageType = "TABLE_EVENT"
	ServerMessageTypeTABLESNAPSHOT  ServerMessageType = "TABLE_SNAPSHOT"
	ServerMessageTypeWELCOME        ServerMessageType = "WELCOME"
)

// Valid indicates whether the value is a known member of the ServerMessageType enum.
func (e ServerMessageType) Valid() bool {
	switch e {
	case ServerMessageTypeCOMMANDRESULT:
		return true
	case ServerMessageTypeERROR:
		return true
	case ServerMessageTypePING:
		return true
	case ServerMessageTypePONG:
		return true
	case ServerMessageTypeRESYNCREQUIRED:
		return true
	case ServerMessageTypeTABLEEVENT:
		return true
	case ServerMessageTypeTABLESNAPSHOT:
		return true
	case ServerMessageTypeWELCOME:
		return true
	default:
		return false
	}
}

// Defines values for TableInfoStatus.
const (
	TableInfoStatusCLOSED TableInfoStatus = "CLOSED"
	TableInfoStatusOPEN   TableInfoStatus = "OPEN"
)

// Valid indicates whether the value is a known member of the TableInfoStatus enum.
func (e TableInfoStatus) Valid() bool {
	switch e {
	case TableInfoStatusCLOSED:
		return true
	case TableInfoStatusOPEN:
		return true
	default:
		return false
	}
}

// Defines values for TableSnapshotPhase.
const (
	TableSnapshotPhaseHANDCOMPLETE      TableSnapshotPhase = "HAND_COMPLETE"
	TableSnapshotPhaseHANDINPROGRESS    TableSnapshotPhase = "HAND_IN_PROGRESS"
	TableSnapshotPhaseWAITINGFORPLAYERS TableSnapshotPhase = "WAITING_FOR_PLAYERS"
)

// Valid indicates whether the value is a known member of the TableSnapshotPhase enum.
func (e TableSnapshotPhase) Valid() bool {
	switch e {
	case TableSnapshotPhaseHANDCOMPLETE:
		return true
	case TableSnapshotPhaseHANDINPROGRESS:
		return true
	case TableSnapshotPhaseWAITINGFORPLAYERS:
		return true
	default:
		return false
	}
}

// Defines values for WelcomeType.
const (
	WelcomeTypeWELCOME WelcomeType = "WELCOME"
)

// Valid indicates whether the value is a known member of the WelcomeType enum.
func (e WelcomeType) Valid() bool {
	switch e {
	case WelcomeTypeWELCOME:
		return true
	default:
		return false
	}
}

// Card Rank + suit, e.g. "As", "Td", "2c".
type Card = string

// ClientMessageType defines model for ClientMessageType.
type ClientMessageType string

// HandView defines model for HandView.
type HandView struct {
	ActionDeadline *time.Time `json:"actionDeadline"`
	BigBlindSeat   int        `json:"bigBlindSeat"`
	Board          []Card     `json:"board"`
	ButtonSeat     int        `json:"buttonSeat"`
	CurrentBet     int64      `json:"currentBet"`

	// DeckCommitment SHA-256 commitment to the deck order (audit).
	DeckCommitment string             `json:"deckCommitment"`
	HandId         openapi_types.UUID `json:"handId"`
	HandNo         int64              `json:"handNo"`
	MinRaise       int64              `json:"minRaise"`
	Pot            int64              `json:"pot"`
	SmallBlindSeat int                `json:"smallBlindSeat"`
	Street         HandViewStreet     `json:"street"`

	// ToActSeat 0 when nobody is to act.
	ToActSeat int `json:"toActSeat"`

	// TurnSeq Sequence of the TURN_STARTED event of the current turn.
	TurnSeq int64 `json:"turnSeq"`
}

// HandViewStreet defines model for HandView.Street.
type HandViewStreet string

// Hello First client frame. Authenticates the connection.
type Hello struct {
	AccessToken   string    `json:"accessToken"`
	ClientVersion string    `json:"clientVersion"`
	DeviceId      *string   `json:"deviceId,omitempty"`
	Type          HelloType `json:"type"`
}

// HelloType defines model for Hello.Type.
type HelloType string

// LegalAction defines model for LegalAction.
type LegalAction struct {
	// Amount CALL - chips to add; ALL_IN - resulting street commitment.
	Amount *int64          `json:"amount,omitempty"`
	Kind   LegalActionKind `json:"kind"`

	// MaxTo BET/RAISE maximum "to" amount (all-in).
	MaxTo *int64 `json:"maxTo,omitempty"`

	// MinTo BET/RAISE minimum "to" amount.
	MinTo *int64 `json:"minTo,omitempty"`
}

// LegalActionKind defines model for LegalAction.Kind.
type LegalActionKind string

// Ping defines model for Ping.
type Ping struct {
	Nonce *string  `json:"nonce,omitempty"`
	Type  PingType `json:"type"`
}

// PingType defines model for Ping.Type.
type PingType string

// Pong defines model for Pong.
type Pong struct {
	Nonce *string  `json:"nonce,omitempty"`
	Type  PongType `json:"type"`
}

// PongType defines model for Pong.Type.
type PongType string

// ProtocolError Connection-level error (not tied to a table command).
type ProtocolError struct {
	// Code An ErrorCode value from the control-api contract.
	Code      string              `json:"code"`
	Message   string              `json:"message"`
	RequestId *string             `json:"requestId,omitempty"`
	TableId   *openapi_types.UUID `json:"tableId,omitempty"`
	Type      ProtocolErrorType   `json:"type"`
}

// ProtocolErrorType defines model for ProtocolError.Type.
type ProtocolErrorType string

// SeatView defines model for SeatView.
type SeatView struct {
	AllIn   bool `json:"allIn"`
	Folded  bool `json:"folded"`
	InHand  bool `json:"inHand"`
	Leaving bool `json:"leaving"`
	Seat    int  `json:"seat"`

	// ShownCards Cards revealed at showdown (public).
	ShownCards *[]Card            `json:"shownCards,omitempty"`
	SittingOut bool               `json:"sittingOut"`
	Stack      int64              `json:"stack"`
	StreetBet  int64              `json:"streetBet"`
	UserId     openapi_types.UUID `json:"userId"`
	Username   string             `json:"username"`
}

// ServerMessageType defines model for ServerMessageType.
type ServerMessageType string

// TableInfo defines model for TableInfo.
type TableInfo struct {
	ActionTimeoutMs int64              `json:"actionTimeoutMs"`
	BigBlind        int64              `json:"bigBlind"`
	BuyInMax        int64              `json:"buyInMax"`
	BuyInMin        int64              `json:"buyInMin"`
	ClubId          openapi_types.UUID `json:"clubId"`
	MaxSeats        int                `json:"maxSeats"`
	Name            string             `json:"name"`
	SmallBlind      int64              `json:"smallBlind"`
	Status          TableInfoStatus    `json:"status"`
}

// TableInfoStatus defines model for TableInfo.Status.
type TableInfoStatus string

// TableSnapshot Complete viewer-sanitized table state; clients replace (never merge) state with it.
type TableSnapshot struct {
	// Hand Present while a hand is in progress or just completed.
	Hand       *HandView          `json:"hand,omitempty"`
	Phase      TableSnapshotPhase `json:"phase"`
	Seats      []SeatView         `json:"seats"`
	Seq        int64              `json:"seq"`
	ServerTime time.Time          `json:"serverTime"`
	Table      TableInfo          `json:"table"`
	TableId    openapi_types.UUID `json:"tableId"`

	// You The viewer's private view (absent for anonymous spectators).
	You *YouView `json:"you,omitempty"`
}

// TableSnapshotPhase defines model for TableSnapshot.Phase.
type TableSnapshotPhase string

// Welcome defines model for Welcome.
type Welcome struct {
	ConnectionId        string             `json:"connectionId"`
	HeartbeatIntervalMs int                `json:"heartbeatIntervalMs"`
	ServerTime          time.Time          `json:"serverTime"`
	Type                WelcomeType        `json:"type"`
	UserId              openapi_types.UUID `json:"userId"`
}

// WelcomeType defines model for Welcome.Type.
type WelcomeType string

// YouView defines model for YouView.
type YouView struct {
	HoleCards    []Card        `json:"holeCards"`
	LegalActions []LegalAction `json:"legalActions"`

	// Seat 0 when the viewer is not seated.
	Seat   int                `json:"seat"`
	UserId openapi_types.UUID `json:"userId"`
}
