// Package controlapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package controlapi

import (
	"time"

	externalRef0 "github.com/bar1287/kofclub/packages/contracts/go/realtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CloseTableResultStatus.
const (
	CloseTableResultStatusCLOSED  CloseTableResultStatus = "CLOSED"
	CloseTableResultStatusCLOSING CloseTableResultStatus = "CLOSING"
)

// Valid indicates whether the value is a known member of the CloseTableResultStatus enum.
func (e CloseTableResultStatus) Valid() bool {
	switch e {
	case CloseTableResultStatusCLOSED:
		return true
	case CloseTableResultStatusCLOSING:
		return true
	default:
		return false
	}
}

// Defines values for ClubMyRole.
const (
	ClubMyRoleADMIN       ClubMyRole = "ADMIN"
	ClubMyRoleAGENT       ClubMyRole = "AGENT"
	ClubMyRoleLessThannil ClubMyRole = "<nil>"
	ClubMyRoleMEMBER      ClubMyRole = "MEMBER"
	ClubMyRoleOWNER       ClubMyRole = "OWNER"
)

// Valid indicates whether the value is a known member of the ClubMyRole enum.
func (e ClubMyRole) Valid() bool {
	switch e {
	case ClubMyRoleADMIN:
		return true
	case ClubMyRoleAGENT:
		return true
	case ClubMyRoleLessThannil:
		return true
	case ClubMyRoleMEMBER:
		return true
	case ClubMyRoleOWNER:
		return true
	default:
		return false
	}
}

// Defines values for ClubRole.
const (
	ClubRoleADMIN  ClubRole = "ADMIN"
	ClubRoleAGENT  ClubRole = "AGENT"
	ClubRoleMEMBER ClubRole = "MEMBER"
	ClubRoleOWNER  ClubRole = "OWNER"
)

// Valid indicates whether the value is a known member of the ClubRole enum.
func (e ClubRole) Valid() bool {
	switch e {
	case ClubRoleADMIN:
		return true
	case ClubRoleAGENT:
		return true
	case ClubRoleMEMBER:
		return true
	case ClubRoleOWNER:
		return true
	default:
		return false
	}
}

// Defines values for ClubStatus.
const (
	ClubStatusACTIVE    ClubStatus = "ACTIVE"
	ClubStatusCLOSED    ClubStatus = "CLOSED"
	ClubStatusSUSPENDED ClubStatus = "SUSPENDED"
)

// Valid indicates whether the value is a known member of the ClubStatus enum.
func (e ClubStatus) Valid() bool {
	switch e {
	case ClubStatusACTIVE:
		return true
	case ClubStatusCLOSED:
		return true
	case ClubStatusSUSPENDED:
		return true
	default:
		return false
	}
}

// Defines values for CreateInviteRequestRole.
const (
	CreateInviteRequestRoleAGENT  CreateInviteRequestRole = "AGENT"
	CreateInviteRequestRoleMEMBER CreateInviteRequestRole = "MEMBER"
)

// Valid indicates whether the value is a known member of the CreateInviteRequestRole enum.
func (e CreateInviteRequestRole) Valid() bool {
	switch e {
	case CreateInviteRequestRoleAGENT:
		return true
	case CreateInviteRequestRoleMEMBER:
		return true
	default:
		return false
	}
}

// Defines values for CreateTableRequestGameType.
const (
	CreateTableRequestGameTypeNLHE CreateTableRequestGameType = "NLHE"
	CreateTableRequestGameTypePLO  CreateTableRequestGameType = "PLO"
)

// Valid indicates whether the value is a known member of the CreateTableRequestGameType enum.
func (e CreateTableRequestGameType) Valid() bool {
	switch e {
	case CreateTableRequestGameTypeNLHE:
		return true
	case CreateTableRequestGameTypePLO:
		return true
	default:
		return false
	}
}

// Defines values for CreateTournamentRequestGameType.
const (
	CreateTournamentRequestGameTypeNLHE CreateTournamentRequestGameType = "NLHE"
	CreateTournamentRequestGameTypePLO  CreateTournamentRequestGameType = "PLO"
)

// Valid indicates whether the value is a known member of the CreateTournamentRequestGameType enum.
func (e CreateTournamentRequestGameType) Valid() bool {
	switch e {
	case CreateTournamentRequestGameTypeNLHE:
		return true
	case CreateTournamentRequestGameTypePLO:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeACCOUNTSUSPENDED         ErrorCode = "ACCOUNT_SUSPENDED"
	ErrorCodeACTIONALREADYPROCESSED   ErrorCode = "ACTION_ALREADY_PROCESSED"
	ErrorCodeALREADYCLUBMEMBER        ErrorCode = "ALREADY_CLUB_MEMBER"
	ErrorCodeALREADYREGISTERED        ErrorCode = "ALREADY_REGISTERED"
	ErrorCodeALREADYSEATED            ErrorCode = "ALREADY_SEATED"
	ErrorCodeAUTHINVALIDCREDENTIALS   ErrorCode = "AUTH_INVALID_CREDENTIALS"
	ErrorCodeAUTHREFRESHINVALID       ErrorCode = "AUTH_REFRESH_INVALID"
	ErrorCodeAUTHREFRESHREUSED        ErrorCode = "AUTH_REFRESH_REUSED"
	ErrorCodeAUTHREQUIRED             ErrorCode = "AUTH_REQUIRED"
	ErrorCodeAUTHSESSIONREVOKED       ErrorCode = "AUTH_SESSION_REVOKED"
	ErrorCodeAUTHTOKENEXPIRED         ErrorCode = "AUTH_TOKEN_EXPIRED"
	ErrorCodeAUTHTOKENINVALID         ErrorCode = "AUTH_TOKEN_INVALID"
	ErrorCodeCLUBBANNED               ErrorCode = "CLUB_BANNED"
	ErrorCodeCLUBNOTFOUND             ErrorCode = "CLUB_NOT_FOUND"
	ErrorCodeCONFLICT                 ErrorCode = "CONFLICT"
	ErrorCodeEMAILTAKEN               ErrorCode = "EMAIL_TAKEN"
	ErrorCodeFORBIDDEN                ErrorCode = "FORBIDDEN"
	ErrorCodeHANDNOTACTIVE            ErrorCode = "HAND_NOT_ACTIVE"
	ErrorCodeHANDNOTFOUND             ErrorCode = "HAND_NOT_FOUND"
	ErrorCodeIDEMPOTENCYCONFLICT      ErrorCode = "IDEMPOTENCY_CONFLICT"
	ErrorCodeILLEGALACTION            ErrorCode = "ILLEGAL_ACTION"
	ErrorCodeINSUFFICIENTCHIPS        ErrorCode = "INSUFFICIENT_CHIPS"
	ErrorCodeINTERNAL                 ErrorCode = "INTERNAL"
	ErrorCodeINVALIDBUYIN             ErrorCode = "INVALID_BUY_IN"
	ErrorCodeINVALIDRAISE             ErrorCode = "INVALID_RAISE"
	ErrorCodeINVITEINVALID            ErrorCode = "INVITE_INVALID"
	ErrorCodeLEDGERINVARIANTVIOLATION ErrorCode = "LEDGER_INVARIANT_VIOLATION"
	ErrorCodeMFAALREADYENABLED        ErrorCode = "MFA_ALREADY_ENABLED"
	ErrorCodeMFAINVALID               ErrorCode = "MFA_INVALID"
	ErrorCodeMFANOTENABLED            ErrorCode = "MFA_NOT_ENABLED"
	ErrorCodeMFAREQUIRED              ErrorCode = "MFA_REQUIRED"
	ErrorCodeNOTCLUBMEMBER            ErrorCode = "NOT_CLUB_MEMBER"
	ErrorCodeNOTENOUGHPLAYERS         ErrorCode = "NOT_ENOUGH_PLAYERS"
	ErrorCodeNOTFOUND                 ErrorCode = "NOT_FOUND"
	ErrorCodeNOTREGISTERED            ErrorCode = "NOT_REGISTERED"
	ErrorCodeNOTYOURTURN              ErrorCode = "NOT_YOUR_TURN"
	ErrorCodePLAYERNOTSEATED          ErrorCode = "PLAYER_NOT_SEATED"
	ErrorCodeRATELIMITED              ErrorCode = "RATE_LIMITED"
	ErrorCodeROLECHANGENOTALLOWED     ErrorCode = "ROLE_CHANGE_NOT_ALLOWED"
	ErrorCodeSEATTAKEN                ErrorCode = "SEAT_TAKEN"
	ErrorCodeSERVICEUNAVAILABLE       ErrorCode = "SERVICE_UNAVAILABLE"
	ErrorCodeSTALEGAMESTATE           ErrorCode = "STALE_GAME_STATE"
	ErrorCodeTABLECLOSED              ErrorCode = "TABLE_CLOSED"
	ErrorCodeTABLEFULL                ErrorCode = "TABLE_FULL"
	ErrorCodeTABLENOTFOUND            ErrorCode = "TABLE_NOT_FOUND"
	ErrorCodeTABLEUNAVAILABLE         ErrorCode = "TABLE_UNAVAILABLE"
	ErrorCodeTOURNAMENTFULL           ErrorCode = "TOURNAMENT_FULL"
	ErrorCodeTOURNAMENTNOTFOUND       ErrorCode = "TOURNAMENT_NOT_FOUND"
	ErrorCodeTOURNAMENTNOTOPEN        ErrorCode = "TOURNAMENT_NOT_OPEN"
	ErrorCodeUSERNAMETAKEN            ErrorCode = "USERNAME_TAKEN"
	ErrorCodeVALIDATIONFAILED         ErrorCode = "VALIDATION_FAILED"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeACCOUNTSUSPENDED:
		return true
	case ErrorCodeACTIONALREADYPROCESSED:
		return true
	case ErrorCodeALREADYCLUBMEMBER:
		return true
	case ErrorCodeALREADYREGISTERED:
		return true
	case ErrorCodeALREADYSEATED:
		return true
	case ErrorCodeAUTHINVALIDCREDENTIALS:
		return true
	case ErrorCodeAUTHREFRESHINVALID:
		return true
	case ErrorCodeAUTHREFRESHREUSED:
		return true
	case ErrorCodeAUTHREQUIRED:
		return true
	case ErrorCodeAUTHSESSIONREVOKED:
		return true
	case ErrorCodeAUTHTOKENEXPIRED:
		return true
	case ErrorCodeAUTHTOKENINVALID:
		return true
	case ErrorCodeCLUBBANNED:
		return true
	case ErrorCodeCLUBNOTFOUND:
		return true
	case ErrorCodeCONFLICT:
		return true
	case ErrorCodeEMAILTAKEN:
		return true
	case ErrorCodeFORBIDDEN:
		return true
	case ErrorCodeHANDNOTACTIVE:
		return true
	case ErrorCodeHANDNOTFOUND:
		return true
	case ErrorCodeIDEMPOTENCYCONFLICT:
		return true
	case ErrorCodeILLEGALACTION:
		return true
	case ErrorCodeINSUFFICIENTCHIPS:
		return true
	case ErrorCodeINTERNAL:
		return true
	case ErrorCodeINVALIDBUYIN:
		return true
	case ErrorCodeINVALIDRAISE:
		return true
	case ErrorCodeINVITEINVALID:
		return true
	case ErrorCodeLEDGERINVARIANTVIOLATION:
		return true
	case ErrorCodeMFAALREADYENABLED:
		return true
	case ErrorCodeMFAINVALID:
		return true
	case ErrorCodeMFANOTENABLED:
		return true
	case ErrorCodeMFAREQUIRED:
		return true
	case ErrorCodeNOTCLUBMEMBER:
		return true
	case ErrorCodeNOTENOUGHPLAYERS:
		return true
	case ErrorCodeNOTFOUND:
		return true
	case ErrorCodeNOTREGISTERED:
		return true
	case ErrorCodeNOTYOURTURN:
		return true
	case ErrorCodePLAYERNOTSEATED:
		return true
	case ErrorCodeRATELIMITED:
		return true
	case ErrorCodeROLECHANGENOTALLOWED:
		return true
	case ErrorCodeSEATTAKEN:
		return true
	case ErrorCodeSERVICEUNAVAILABLE:
		return true
	case ErrorCodeSTALEGAMESTATE:
		return true
	case ErrorCodeTABLECLOSED:
		return true
	case ErrorCodeTABLEFULL:
		return true
	case ErrorCodeTABLENOTFOUND:
		return true
	case ErrorCodeTABLEUNAVAILABLE:
		return true
	case ErrorCodeTOURNAMENTFULL:
		return true
	case ErrorCodeTOURNAMENTNOTFOUND:
		return true
	case ErrorCodeTOURNAMENTNOTOPEN:
		return true
	case ErrorCodeUSERNAMETAKEN:
		return true
	case ErrorCodeVALIDATIONFAILED:
		return true
	default:
		return false
	}
}

// Defines values for HandDetailStatus.
const (
	HandDetailStatusCOMPLETED HandDetailStatus = "COMPLETED"
	HandDetailStatusVOIDED    HandDetailStatus = "VOIDED"
)

// Valid indicates whether the value is a known member of the HandDetailStatus enum.
func (e HandDetailStatus) Valid() bool {
	switch e {
	case HandDetailStatusCOMPLETED:
		return true
	case HandDetailStatusVOIDED:
		return true
	default:
		return false
	}
}

// Defines values for HandDetailViewerRole.
const (
	HandDetailViewerRoleCLUBSTAFF     HandDetailViewerRole = "CLUB_STAFF"
	HandDetailViewerRolePARTICIPANT   HandDetailViewerRole = "PARTICIPANT"
	HandDetailViewerRolePLATFORMADMIN HandDetailViewerRole = "PLATFORM_ADMIN"
)

// Valid indicates whether the value is a known member of the HandDetailViewerRole enum.
func (e HandDetailViewerRole) Valid() bool {
	switch e {
	case HandDetailViewerRoleCLUBSTAFF:
		return true
	case HandDetailViewerRolePARTICIPANT:
		return true
	case HandDetailViewerRolePLATFORMADMIN:
		return true
	default:
		return false
	}
}

// Defines values for HandSummaryStatus.
const (
	HandSummaryStatusCOMPLETED HandSummaryStatus = "COMPLETED"
	HandSummaryStatusVOIDED    HandSummaryStatus = "VOIDED"
)

// Valid indicates whether the value is a known member of the HandSummaryStatus enum.
func (e HandSummaryStatus) Valid() bool {
	switch e {
	case HandSummaryStatusCOMPLETED:
		return true
	case HandSummaryStatusVOIDED:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	HealthStatusStatusDraining    HealthStatusStatus = "draining"
	HealthStatusStatusOk          HealthStatusStatus = "ok"
	HealthStatusStatusUnavailable HealthStatusStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case HealthStatusStatusDraining:
		return true
	case HealthStatusStatusOk:
		return true
	case HealthStatusStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for InviteRole.
const (
	InviteRoleAGENT  InviteRole = "AGENT"
	InviteRoleMEMBER InviteRole = "MEMBER"
)

// Valid indicates whether the value is a known member of the InviteRole enum.
func (e InviteRole) Valid() bool {
	switch e {
	case InviteRoleAGENT:
		return true
	case InviteRoleMEMBER:
		return true
	default:
		return false
	}
}

// Defines values for InviteStatus.
const (
	InviteStatusACTIVE    InviteStatus = "ACTIVE"
	InviteStatusEXHAUSTED InviteStatus = "EXHAUSTED"
	InviteStatusEXPIRED   InviteStatus = "EXPIRED"
	InviteStatusREVOKED   InviteStatus = "REVOKED"
)

// Valid indicates whether the value is a known member of the InviteStatus enum.
func (e InviteStatus) Valid() bool {
	switch e {
	case InviteStatusACTIVE:
		return true
	case InviteStatusEXHAUSTED:
		return true
	case InviteStatusEXPIRED:
		return true
	case InviteStatusREVOKED:
		return true
	default:
		return false
	}
}

// Defines values for LeaveResultStatus.
const (
	LeaveResultStatusLEAVINGAFTERHAND LeaveResultStatus = "LEAVING_AFTER_HAND"
	LeaveResultStatusLEFT             LeaveResultStatus = "LEFT"
)

// Valid indicates whether the value is a known member of the LeaveResultStatus enum.
func (e LeaveResultStatus) Valid() bool {
	switch e {
	case LeaveResultStatusLEAVINGAFTERHAND:
		return true
	case LeaveResultStatusLEFT:
		return true
	default:
		return false
	}
}

// Defines values for LedgerAccountKind.
const (
	LedgerAccountKindCLUBTREASURY   LedgerAccountKind = "CLUB_TREASURY"
	LedgerAccountKindMEMBERWALLET   LedgerAccountKind = "MEMBER_WALLET"
	LedgerAccountKindTABLESTACK     LedgerAccountKind = "TABLE_STACK"
	LedgerAccountKindTOURNAMENTPOOL LedgerAccountKind = "TOURNAMENT_POOL"
)

// Valid indicates whether the value is a known member of the LedgerAccountKind enum.
func (e LedgerAccountKind) Valid() bool {
	switch e {
	case LedgerAccountKindCLUBTREASURY:
		return true
	case LedgerAccountKindMEMBERWALLET:
		return true
	case LedgerAccountKindTABLESTACK:
		return true
	case LedgerAccountKindTOURNAMENTPOOL:
		return true
	default:
		return false
	}
}

// Defines values for LedgerKind.
const (
	LedgerKindADMINADJUSTMENT   LedgerKind = "ADMIN_ADJUSTMENT"
	LedgerKindCLUBDEDUCTION     LedgerKind = "CLUB_DEDUCTION"
	LedgerKindCLUBGRANT         LedgerKind = "CLUB_GRANT"
	LedgerKindHANDSETTLEMENT    LedgerKind = "HAND_SETTLEMENT"
	LedgerKindPROMOTIONALCREDIT LedgerKind = "PROMOTIONAL_CREDIT"
	LedgerKindREVERSAL          LedgerKind = "REVERSAL"
	LedgerKindTABLEBUYIN        LedgerKind = "TABLE_BUY_IN"
	LedgerKindTABLECASHOUT      LedgerKind = "TABLE_CASH_OUT"
	LedgerKindTOURNAMENTBUYIN   LedgerKind = "TOURNAMENT_BUY_IN"
	LedgerKindTOURNAMENTPAYOUT  LedgerKind = "TOURNAMENT_PAYOUT"
	LedgerKindTOURNAMENTREFUND  LedgerKind = "TOURNAMENT_REFUND"
)

// Valid indicates whether the value is a known member of the LedgerKind enum.
func (e LedgerKind) Valid() bool {
	switch e {
	case LedgerKindADMINADJUSTMENT:
		return true
	case LedgerKindCLUBDEDUCTION:
		return true
	case LedgerKindCLUBGRANT:
		return true
	case LedgerKindHANDSETTLEMENT:
		return true
	case LedgerKindPROMOTIONALCREDIT:
		return true
	case LedgerKindREVERSAL:
		return true
	case LedgerKindTABLEBUYIN:
		return true
	case LedgerKindTABLECASHOUT:
		return true
	case LedgerKindTOURNAMENTBUYIN:
		return true
	case LedgerKindTOURNAMENTPAYOUT:
		return true
	case LedgerKindTOURNAMENTREFUND:
		return true
	default:
		return false
	}
}

// Defines values for LedgerTransactionActorType.
const (
	LedgerTransactionActorTypeGAMESERVICE LedgerTransactionActorType = "GAME_SERVICE"
	LedgerTransactionActorTypeSYSTEM      LedgerTransactionActorType = "SYSTEM"
	LedgerTransactionActorTypeUSER        LedgerTransactionActorType = "USER"
)

// Valid indicates whether the value is a known member of the LedgerTransactionActorType enum.
func (e LedgerTransactionActorType) Valid() bool {
	switch e {
	case LedgerTransactionActorTypeGAMESERVICE:
		return true
	case LedgerTransactionActorTypeSYSTEM:
		return true
	case LedgerTransactionActorTypeUSER:
		return true
	default:
		return false
	}
}

// Defines values for MemberStatus.
const (
	MemberStatusACTIVE MemberStatus = "ACTIVE"
	MemberStatusBANNED MemberStatus = "BANNED"
	MemberStatusLEFT   MemberStatus = "LEFT"
)

// Valid indicates whether the value is a known member of the MemberStatus enum.
func (e MemberStatus) Valid() bool {
	switch e {
	case MemberStatusACTIVE:
		return true
	case MemberStatusBANNED:
		return true
	case MemberStatusLEFT:
		return true
	default:
		return false
	}
}

// Defines values for PlatformRole.
const (
	PlatformRolePLATFORMADMIN PlatformRole = "PLATFORM_ADMIN"
	PlatformRoleUSER          PlatformRole = "USER"
)

// Valid indicates whether the value is a known member of the PlatformRole enum.
func (e PlatformRole) Valid() bool {
	switch e {
	case PlatformRolePLATFORMADMIN:
		return true
	case PlatformRoleUSER:
		return true
	default:
		return false
	}
}

// Defines values for ReviewRiskEventRequestDisposition.
const (
	ReviewRiskEventRequestDispositionCONFIRMED ReviewRiskEventRequestDisposition = "CONFIRMED"
	ReviewRiskEventRequestDispositionDISMISSED ReviewRiskEventRequestDisposition = "DISMISSED"
	ReviewRiskEventRequestDispositionESCALATED ReviewRiskEventRequestDisposition = "ESCALATED"
)

// Valid indicates whether the value is a known member of the ReviewRiskEventRequestDisposition enum.
func (e ReviewRiskEventRequestDisposition) Valid() bool {
	switch e {
	case ReviewRiskEventRequestDispositionCONFIRMED:
		return true
	case ReviewRiskEventRequestDispositionDISMISSED:
		return true
	case ReviewRiskEventRequestDispositionESCALATED:
		return true
	default:
		return false
	}
}

// Defines values for RiskEventDisposition.
const (
	RiskEventDispositionCONFIRMED   RiskEventDisposition = "CONFIRMED"
	RiskEventDispositionDISMISSED   RiskEventDisposition = "DISMISSED"
	RiskEventDispositionESCALATED   RiskEventDisposition = "ESCALATED"
	RiskEventDispositionLessThannil RiskEventDisposition = "<nil>"
)

// Valid indicates whether the value is a known member of the RiskEventDisposition enum.
func (e RiskEventDisposition) Valid() bool {
	switch e {
	case RiskEventDispositionCONFIRMED:
		return true
	case RiskEventDispositionDISMISSED:
		return true
	case RiskEventDispositionESCALATED:
		return true
	case RiskEventDispositionLessThannil:
		return true
	default:
		return false
	}
}

// Defines values for RiskEventSeverity.
const (
	RiskEventSeverityHIGH   RiskEventSeverity = "HIGH"
	RiskEventSeverityLOW    RiskEventSeverity = "LOW"
	RiskEventSeverityMEDIUM RiskEventSeverity = "MEDIUM"
)

// Valid indicates whether the value is a known member of the RiskEventSeverity enum.
func (e RiskEventSeverity) Valid() bool {
	switch e {
	case RiskEventSeverityHIGH:
		return true
	case RiskEventSeverityLOW:
		return true
	case RiskEventSeverityMEDIUM:
		return true
	default:
		return false
	}
}

// Defines values for TableStatus.
const (
	TableStatusCLOSED TableStatus = "CLOSED"
	TableStatusOPEN   TableStatus = "OPEN"
)

// Valid indicates whether the value is a known member of the TableStatus enum.
func (e TableStatus) Valid() bool {
	switch e {
	case TableStatusCLOSED:
		return true
	case TableStatusOPEN:
		return true
	default:
		return false
	}
}

// Defines values for TableDetailStatus.
const (
	TableDetailStatusCLOSED TableDetailStatus = "CLOSED"
	TableDetailStatusOPEN   TableDetailStatus = "OPEN"
)

// Valid indicates whether the value is a known member of the TableDetailStatus enum.
func (e TableDetailStatus) Valid() bool {
	switch e {
	case TableDetailStatusCLOSED:
		return true
	case TableDetailStatusOPEN:
		return true
	default:
		return false
	}
}

// Defines values for TournamentStartMode.
const (
	TournamentStartModeSCHEDULED TournamentStartMode = "SCHEDULED"
	TournamentStartModeSITANDGO  TournamentStartMode = "SIT_AND_GO"
)

// Valid indicates whether the value is a known member of the TournamentStartMode enum.
func (e TournamentStartMode) Valid() bool {
	switch e {
	case TournamentStartModeSCHEDULED:
		return true
	case TournamentStartModeSITANDGO:
		return true
	default:
		return false
	}
}

// Defines values for TournamentStatus.
const (
	TournamentStatusCANCELLED   TournamentStatus = "CANCELLED"
	TournamentStatusFINISHED    TournamentStatus = "FINISHED"
	TournamentStatusREGISTERING TournamentStatus = "REGISTERING"
	TournamentStatusRUNNING     TournamentStatus = "RUNNING"
)

// Valid indicates whether the value is a known member of the TournamentStatus enum.
func (e TournamentStatus) Valid() bool {
	switch e {
	case TournamentStatusCANCELLED:
		return true
	case TournamentStatusFINISHED:
		return true
	case TournamentStatusREGISTERING:
		return true
	case TournamentStatusRUNNING:
		return true
	default:
		return false
	}
}

// Defines values for UpdateAccountStatusRequestStatus.
const (
	UpdateAccountStatusRequestStatusACTIVE    UpdateAccountStatusRequestStatus = "ACTIVE"
	UpdateAccountStatusRequestStatusSUSPENDED UpdateAccountStatusRequestStatus = "SUSPENDED"
)

// Valid indicates whether the value is a known member of the UpdateAccountStatusRequestStatus enum.
func (e UpdateAccountStatusRequestStatus) Valid() bool {
	switch e {
	case UpdateAccountStatusRequestStatusACTIVE:
		return true
	case UpdateAccountStatusRequestStatusSUSPENDED:
		return true
	default:
		return false
	}
}

// Defines values for UpdateMemberRequestRole.
const (
	UpdateMemberRequestRoleADMIN  UpdateMemberRequestRole = "ADMIN"
	UpdateMemberRequestRoleAGENT  UpdateMemberRequestRole = "AGENT"
	UpdateMemberRequestRoleMEMBER UpdateMemberRequestRole = "MEMBER"
)

// Valid indicates whether the value is a known member of the UpdateMemberRequestRole enum.
func (e UpdateMemberRequestRole) Valid() bool {
	switch e {
	case UpdateMemberRequestRoleADMIN:
		return true
	case UpdateMemberRequestRoleAGENT:
		return true
	case UpdateMemberRequestRoleMEMBER:
		return true
	default:
		return false
	}
}

// Defines values for UpdateMemberRequestStatus.
const (
	UpdateMemberRequestStatusACTIVE UpdateMemberRequestStatus = "ACTIVE"
	UpdateMemberRequestStatusBANNED UpdateMemberRequestStatus = "BANNED"
)

// Valid indicates whether the value is a known member of the UpdateMemberRequestStatus enum.
func (e UpdateMemberRequestStatus) Valid() bool {
	switch e {
	case UpdateMemberRequestStatusACTIVE:
		return true
	case UpdateMemberRequestStatusBANNED:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	UserStatusACTIVE    UserStatus = "ACTIVE"
	UserStatusDELETED   UserStatus = "DELETED"
	UserStatusSUSPENDED UserStatus = "SUSPENDED"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case UserStatusACTIVE:
		return true
	case UserStatusDELETED:
		return true
	case UserStatusSUSPENDED:
		return true
	default:
		return false
	}
}

// Defines values for AuthTransport.
const (
	AuthTransportBody   AuthTransport = "body"
	AuthTransportCookie AuthTransport = "cookie"
)

// Valid indicates whether the value is a known member of the AuthTransport enum.
func (e AuthTransport) Valid() bool {
	switch e {
	case AuthTransportBody:
		return true
	case AuthTransportCookie:
		return true
	default:
		return false
	}
}

// Defines values for AdminRiskEventsParamsStatus.
const (
	AdminRiskEventsParamsStatusOPEN     AdminRiskEventsParamsStatus = "OPEN"
	AdminRiskEventsParamsStatusREVIEWED AdminRiskEventsParamsStatus = "REVIEWED"
)

// Valid indicates whether the value is a known member of the AdminRiskEventsParamsStatus enum.
func (e AdminRiskEventsParamsStatus) Valid() bool {
	switch e {
	case AdminRiskEventsParamsStatusOPEN:
		return true
	case AdminRiskEventsParamsStatusREVIEWED:
		return true
	default:
		return false
	}
}

// Defines values for LoginParamsXAuthTransport.
const (
	LoginParamsXAuthTransportBody   LoginParamsXAuthTransport = "body"
	LoginParamsXAuthTransportCookie LoginParamsXAuthTransport = "cookie"
)

// Valid indicates whether the value is a known member of the LoginParamsXAuthTransport enum.
func (e LoginParamsXAuthTransport) Valid() bool {
	switch e {
	case LoginParamsXAuthTransportBody:
		return true
	case LoginParamsXAuthTransportCookie:
		return true
	default:
		return false
	}
}

// Defines values for RefreshParamsXAuthTransport.
const (
	RefreshParamsXAuthTransportBody   RefreshParamsXAuthTransport = "body"
	RefreshParamsXAuthTransportCookie RefreshParamsXAuthTransport = "cookie"
)

// Valid indicates whether the value is a known member of the RefreshParamsXAuthTransport enum.
func (e RefreshParamsXAuthTransport) Valid() bool {
	switch e {
	case RefreshParamsXAuthTransportBody:
		return true
	case RefreshParamsXAuthTransportCookie:
		return true
	default:
		return false
	}
}

// Defines values for RegisterParamsXAuthTransport.
const (
	RegisterParamsXAuthTransportBody   RegisterParamsXAuthTransport = "body"
	RegisterParamsXAuthTransportCookie RegisterParamsXAuthTransport = "cookie"
)

// Valid indicates whether the value is a known member of the RegisterParamsXAuthTransport enum.
func (e RegisterParamsXAuthTransport) Valid() bool {
	switch e {
	case RegisterParamsXAuthTransportBody:
		return true
	case RegisterParamsXAuthTransportCookie:
		return true
	default:
		return false
	}
}

// AdminClub defines model for AdminClub.
type AdminClub struct {
	// CreatedAt UTC RFC 3339 timestamp
	CreatedAt     Timestamp  `json:"createdAt"`
	Id            Uuid       `json:"id"`
	MemberCount   int        `json:"memberCount"`
	Name          string     `json:"name"`
	OpenTables    int        `json:"openTables"`
	OwnerUserId   Uuid       `json:"ownerUserId"`
	OwnerUsername string     `json:"ownerUsername"`
	Status        ClubStatus `json:"status"`
}

// AdminClubPage defines model for AdminClubPage.
type AdminClubPage struct {
	Items      []AdminClub `json:"items"`
	NextCursor *string     `json:"nextCursor"`
}

// AdminUser defines model for AdminUser.
type AdminUser struct {
	ActiveSessions int `json:"activeSessions"`
	ClubCount      int `json:"clubCount"`

	// CreatedAt UTC RFC 3339 timestamp
	CreatedAt    Timestamp    `json:"createdAt"`
	Email        string       `json:"email"`
	Id           Uuid         `json:"id"`
	PlatformRole PlatformRole `json:"platformRole"`
	Status       UserStatus   `json:"status"`
	Username     string       `json:"username"`
}

// AdminUserPage defines model for AdminUserPage.
type AdminUserPage struct {
	Items      []AdminUser `json:"items"`
	NextCursor *string     `json:"nextCursor"`
}

// AuditPage defines model for AuditPage.
type AuditPage struct {
	Items      []AuditRecord `json:"items"`
	NextCursor *string       `json:"nextCursor"`
}

// AuditRecord defines model for AuditRecord.
type AuditRecord struct {
	Action        string                  `json:"action"`
	ActorUserId   *openapi_types.UUID     `json:"actorUserId"`
	ActorUsername *string                 `json:"actorUsername"`
	After         *map[string]interface{} `json:"after"`
	Before        *map[string]interface{} `json:"before"`
	ClubId        *openapi_types.UUID     `json:"clubId"`

	// CreatedAt UTC RFC 3339 timestamp
	CreatedAt  Timestamp `json:"createdAt"`
	Id         Uuid      `json:"id"`
	ObjectId   *string   `json:"objectId"`
	ObjectType string    `json:"objectType"`
	RequestId  *string   `json:"requestId"`
}

// AuthResult defines model for AuthResult.
type AuthResult struct {
	// AccessToken EdDSA JWT, ~15 minutes
	AccessToken string `json:"accessToken"`

	// AccessTokenExpiresAt UTC RFC 3339 timestamp
	AccessTokenExpiresAt Timestamp `json:"accessTokenExpiresAt"`

	// RefreshToken Opaque token; omitted when cookie transport is used
	RefreshToken *string `json:"refreshToken,omitempty"`

	// RefreshTokenExpiresAt UTC RFC 3339 timestamp
	RefreshTokenExpiresAt Timestamp `json:"refreshTokenExpiresAt"`
	SessionId             Uuid      `json:"sessionId"`
	User                  User      `json:"user"`
}

// BlindLevel defines model for BlindLevel.
type BlindLevel struct {
	// BigBlind Integer amount of virtual chips (no monetary value).
	BigBlind ChipAmount `json:"bigBlind"`
	Level    int        `json:"level"`

	// SmallBlind Integer amount of virtual chips (no monetary value).
	SmallBlind ChipAmount `json:"smallBlind"`
}

// ChipAmount Integer amount of virtual chips (no monetary value).
type ChipAmount = int64

// ChipMovementRequest defines model for ChipMovementRequest.
type ChipMovementRequest struct {
	Amount int64   `json:"amount"`
	Note   *string `json:"note,omitempty"`
	UserId Uuid    `json:"userId"`
}

// CloseTableResult defines model for CloseTableResult.
type CloseTableResult struct {
	// Seated Players still seated (0 once CLOSED).
	Seated int `json:"seated"`

	// Status CLOSING while a hand finishes; seats are then cashed out.
	Status  CloseTableResultStatus `json:"status"`
	TableId Uuid                   `json:"tableId"`
}

// CloseTableResultStatus CLOSING while a hand finishes; seats are then cashed out.
type CloseTableResultStatus string

// Club defines model for Club.
type Club struct {
	// CreatedAt UTC RFC 3339 timestamp
	CreatedAt   Timestamp `json:"createdAt"`
	Description *string   `json:"description"`
	Id          Uuid      `json:"id"`

	// JoinCode Visible to AGENT and above only.
	JoinCode    *string `json:"joinCode,omitempty"`
	MemberCount *int    `json:"memberCount,omitempty"`

	// MyRole Null when viewed through platform-admin oversight.
	MyRole      *ClubMyRole `json:"myRole"`
	Name        string      `json:"name"`
	OwnerUserId Uuid        `json:"ownerUserId"`
	Status      ClubStatus  `json:"status"`
}

// ClubMyRole Null when viewed through platform-admin oversight.
type ClubMyRole string

// ClubList defines model for ClubList.
type ClubList struct {
	Items []Club `json:"items"`
}

// ClubRole defines model for ClubRole.
type ClubRole string

// ClubStatus defines model for ClubStatus.
type ClubStatus string

// CreateClubRequest defines model for CreateClubRequest.
type CreateClubRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreateInviteRequest defines model for CreateInviteRequest.
type CreateInviteRequest struct {
	ExpiresInHours *int                     `json:"expiresInHours,omitempty"`
	MaxUses        *int                     `json:"maxUses,omitempty"`
	Role           *CreateInviteRequestRole `json:"role,omitempty"`
}

// CreateInviteRequestRole defines model for CreateInviteRequest.Role.
type CreateInviteRequestRole string

// CreateTableRequest defines model for CreateTableRequest.
type CreateTableRequest struct {
	ActionTimeoutSec *int `json:"actionTimeoutSec,omitempty"`

	// BigBlind Integer amount of virtual chips (no monetary value).
	BigBlind ChipAmount `json:"bigBlind"`

	// BuyInMax Integer amount of virtual chips (no monetary value).
	BuyInMax ChipAmount `json:"buyInMax"`

	// BuyInMin Integer amount of virtual chips (no monetary value).
	BuyInMin ChipAmount `json:"buyInMin"`

	// GameType See GameType. Fixed for the table's lifetime.
	GameType *CreateTableRequestGameType `json:"gameType,omitempty"`
	MaxSeats *int                        `json:"maxSeats,omitempty"`
	Name     string                      `json:"name"`

	// SmallBlind Integer amount of virtual chips (no monetary value).
	SmallBlind ChipAmount `json:"smallBlind"`
}

// CreateTableRequestGameType See GameType. Fixed for the table's lifetime.
type CreateTableRequestGameType string

// CreateTournamentRequest defines model for CreateTournamentRequest.
type CreateTournamentRequest struct {
	ActionTimeoutSec *int `json:"actionTimeoutSec,omitempty"`

	// BigBlind Level 1 big blind (at most a tenth of the starting stack).
	BigBlind int64 `json:"bigBlind"`

	// BuyIn Club chips paid into the prize pool (0 = freeroll).
	BuyIn            int64                            `json:"buyIn"`
	GameType         *CreateTournamentRequestGameType `json:"gameType,omitempty"`
	LevelDurationSec int                              `json:"levelDurationSec"`
	MaxPlayers       int                              `json:"maxPlayers"`
	MinPlayers       *int                             `json:"minPlayers,omitempty"`
	Name             string                           `json:"name"`
	SeatsPerTable    *int                             `json:"seatsPerTable,omitempty"`

	// SmallBlind Level 1 small blind; later levels follow a standard progression.
	SmallBlind int64 `json:"smallBlind"`

	// StartMode SIT_AND_GO starts when maxPlayers registered; SCHEDULED at startsAt (cancelled and refunded if fewer than minPlayers).
	StartMode     TournamentStartMode `json:"startMode"`
	StartingStack int64               `json:"startingStack"`

	// StartsAt Required for SCHEDULED (in the future); not allowed for SIT_AND_GO.
	StartsAt *time.Time `json:"startsAt,omitempty"`
}

// CreateTournamentRequestGameType defines model for CreateTournamentRequest.GameType.
type CreateTournamentRequestGameType string

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	// Code Stable machine-readable error codes shared by HTTP and realtime APIs.
	// Clients must branch on `code`, never on `message`.
	Code    ErrorCode               `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable summary (not for programmatic use).
	Message   string `json:"message"`
	RequestId string `json:"requestId"`
}

// ErrorCode Stable machine-readable error codes shared by HTTP and realtime APIs.
// Clients must branch on `code`, never on `message`.
type ErrorCode string

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error ErrorBody `json:"error"`
}

// HandDetail defines model for HandDetail.
type HandDetail struct {
	// BigBlind Integer amount of virtual chips (no monetary value).
	BigBlind   ChipAmount          `json:"bigBlind"`
	Board      []externalRef0.Card `json:"board"`
	ButtonSeat int                 `json:"buttonSeat"`
	ClubId     Uuid                `json:"clubId"`
	ClubName   string              `json:"clubName"`

	// DeckCommitment SHA-256 commitment to the shuffled deck (internal audit).
	DeckCommitment string `json:"deckCommitment"`

	// EndedAt UTC RFC 3339 timestamp
	EndedAt Timestamp `json:"endedAt"`

	// Events Public action log of the hand (never contains unrevealed cards).
	Events []HandEventRecord `json:"events"`

	// GameType NLHE = No-Limit Texas Hold'em (2 hole cards). PLO = Pot-Limit Omaha
	// (4 hole cards; a hand uses exactly two of them and three board cards;
	// bets and raises are capped at the pot).
	GameType externalRef0.GameType `json:"gameType"`
	HandNo   int64                 `json:"handNo"`
	Id       Uuid                  `json:"id"`

	// MyHoleCards The viewer's own hole cards; null for non-participants.
	MyHoleCards *[]externalRef0.Card `json:"myHoleCards"`

	// MyNet The viewer's result; null when the viewer did not play or the hand was voided.
	MyNet       *int64            `json:"myNet"`
	PlayerCount int               `json:"playerCount"`
	Players     []HandParticipant `json:"players"`

	// Pot Integer amount of virtual chips (no monetary value).
	Pot ChipAmount `json:"pot"`

	// SmallBlind Integer amount of virtual chips (no monetary value).
	SmallBlind ChipAmount `json:"smallBlind"`

	// StartedAt UTC RFC 3339 timestamp
	StartedAt    Timestamp            `json:"startedAt"`
	Status       HandDetailStatus     `json:"status"`
	TableId      Uuid                 `json:"tableId"`
	TableName    string               `json:"tableName"`
	TournamentId *openapi_types.UUID  `json:"tournamentId"`
	ViewerRole   HandDetailViewerRole `json:"viewerRole"`
	VoidReason   *string              `json:"voidReason"`
}

// HandDetailStatus defines model for HandDetail.Status.
type HandDetailStatus string

// HandDetailViewerRole defines model for HandDetail.ViewerRole.
type HandDetailViewerRole string

// HandEventRecord defines model for HandEventRecord.
type HandEventRecord struct {
	// CreatedAt UTC RFC 3339 timestamp
	CreatedAt Timestamp `json:"createdAt"`

	// Event Ordered table event (discriminated by kind). Private fields only appear in the recipient's copy.
	Event externalRef0.TableEventPayload `json:"event"`
	Seq   int64                          `json:"seq"`
}

// HandParticipant defines model for HandParticipant.
type HandParticipant struct {
	Contributed *int64 `json:"contributed"`
	EndingStack *int64 `json:"endingStack"`
	Folded      *bool  `json:"folded"`
	Net         *int64 `json:"net"`
	Seat        int    `json:"seat"`

	// ShownCards Cards revealed at showdown (public); null when not shown.
	ShownCards *[]externalRef0.Card `json:"shownCards"`

	// StartingStack Integer amount of virtual chips (no monetary value).
	StartingStack ChipAmount `json:"startingStack"`
	UserId        Uuid       `json:"userId"`
	Username      string     `json:"username"`
	Won           *int64     `json:"won"`
}

// HandSummary No additionalProperties restriction because HandDetail extends it (allOf).
type HandSummary struct {
	// BigBlind Integer amount of virtual chips (no monetary value).
	BigBlind ChipAmount          `json:"bigBlind"`
	Board    []externalRef0.Card `json:"board"`
	ClubId   Uuid                `json:"clubId"`
	ClubName string              `json:"clubName"`

	// EndedAt UTC RFC 3339 timestamp
	EndedAt Timestamp `json:"endedAt"`

	// GameType NLHE = No-Limit Texas Hold'em (2 hole cards). PLO = Pot-Limit Omaha
	// (4 hole cards; a hand uses exactly two of them and three board cards;
	// bets and raises are capped at the pot).
	GameType externalRef0.GameType `json:"gameType"`
	HandNo   int64                 `json:"handNo"`
	Id       Uuid                  `json:"id"`

	// MyNet The viewer's result; null when the viewer did not play or the hand was voided.
	MyNet       *int64 `json:"myNet"`
	PlayerCount int    `json:"playerCount"`

	// Pot Integer amount of virtual chips (no monetary value).
	Pot ChipAmount `json:"pot"`

	// SmallBlind Integer amount of virtual chips (no monetary value).
	SmallBlind ChipAmount `json:"smallBlind"`

	// StartedAt UTC RFC 3339 timestamp
	StartedAt    Timestamp           `json:"startedAt"`
	Status       HandSummaryStatus   `json:"status"`
	TableId      Uuid                `json:"tableId"`
	TableName    string              `json:"tableName"`
	TournamentId *openapi_types.UUID `json:"tournamentId"`
}

// HandSummaryStatus defines model for HandSummary.Status.
type HandSummaryStatus string

// HandSummaryPage defines model for HandSummaryPage.
type HandSummaryPage struct {
	Items      []HandSummary `json:"items"`
	NextCursor *string       `json:"nextCursor"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Checks  *map[string]string `json:"checks,omitempty"`
	Service string             `json:"service"`
	Status  HealthStatusStatus `json:"status"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// Invite defines model for Invite.
type Invite struct {
	ClubId Uuid `json:"clubId"`

	// CreatedAt UTC RFC 3339 timestamp
	CreatedAt Timestamp `json:"createdAt"`

	// ExpiresAt UTC RFC 3339 timestamp
	ExpiresAt Timestamp    `json:"expiresAt"`
	Id        Uuid         `json:"id"`
	MaxUses   int          `json:"maxUses"`
	RevokedAt *time.Time   `json:"revokedAt"`
	Role      InviteRole   `json:"role"`
	Status    InviteStatus `json:"status"`
	UseCount  int          `json:"useCount"`
}

// InviteRole defines model for Invite.Role.
type InviteRole string

// InviteStatus defines model for Invite.Status.
type InviteStatus string

// InviteCreated defines model for InviteCreated.
type InviteCreated struct {
	// Code Plaintext invite code, returned only once.
	Code   string `json:"code"`
	Invite Invite `json:"invite"`
}

// InviteList defines model for InviteList.
type InviteList struct {
	Items []Invite `json:"items"`
}

// JoinClubRequest defines model for JoinClubRequest.
type JoinClubRequest struct {
	// Code Club join code (8 chars) or invite code (12 chars); case-insensitive.
	Code string `json:"code"`
}

// LeaveResult defines model for LeaveResult.
type LeaveResult struct {
	// CashOut Integer amount of virtual chips (no monetary value).
	CashOut ChipAmount        `json:"cashOut"`
	Status  LeaveResultStatus `json:"status"`
	TableId Uuid              `json:"tableId"`
}

// LeaveResultStatus defines model for LeaveResult.Status.
type LeaveResultStatus string

// LedgerAccountKind defines model for LedgerAccountKind.
type LedgerAccountKind string

// LedgerEntry defines model for LedgerEntry.
type LedgerEntry struct {
	AccountId   Uuid              `json:"accountId"`
	AccountKind LedgerAccountKind `json:"accountKind"`

	// Amount Integer amount of virtual chips (no monetary value).
	Amount ChipAmount `json:"amount"`

	// BalanceAfter Integer amount of virtual chips (no monetary value).
	BalanceAfter  ChipAmount          `json:"balanceAfter"`
	OwnerId       Uuid                `json:"ownerId"`
	OwnerUsername *string             `json:"ownerUsername"`
	TableId       *openapi_types.UUID `json:"tableId"`
}

// LedgerKind defines model for LedgerKind.
type LedgerKind string

// LedgerSummary defines model for LedgerSummary.
type LedgerSummary struct {
	// AtTables Integer amount of virtual chips (no monetary value).
	AtTables ChipAmount `json:"atTables"`
	ClubId   Uuid       `json:"clubId"`
	Holders  int        `json:"holders"`

	// InTournaments Integer amount of virtual chips (no monetary value).
	InTournaments ChipAmount `json:"inTournaments"`

	// InWallets Integer amount of virtual chips (no monetary value).
	InWallets ChipAmount `json:"inWallets"`

	// Issued Integer amount of virtual chips (no monetary value).
	Issued ChipAmount `json:"issued"`
}

// LedgerTransaction defines model for LedgerTransaction.
type LedgerTransaction struct {
	ActorType     LedgerTransactionActorType `json:"actorType"`
	ActorUserId   *openapi_types.UUID        `json:"actorUserId"`
	ActorUsername *string                    `json:"actorUsername"`

	// CreatedAt UTC RFC 3339 timestamp
	CreatedAt     Timestamp              `json:"createdAt"`
	Entries       []LedgerEntry          `json:"entries"`
	Id            Uuid                   `json:"id"`
	Kind          LedgerKind             `json:"kind"`
	Metadata      map[string]interface{} `json:"metadata"`
	ReferenceId   *string                `json:"referenceId"`
	ReferenceType *string                `json:"referenceType"`
	ReversesTxId  *openapi_types.UUID    `json:"reversesTxId"`
}

// LedgerTransactionActorType defines model for LedgerTransaction.ActorType.
type LedgerTransactionActorType string

// LedgerTransactionPage defines model for LedgerTransactionPage.
type LedgerTransactionPage struct {
	Items      []LedgerTransaction `json:"items"`
	NextCursor *string             `json:"nextCursor"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	DeviceId *string `json:"deviceId,omitempty"`

	// Login Email or username
	Login string `json:"login"`

	// MfaCode Six-digit authenticator code or a recovery code, for accounts with
	// two-factor authentication. Without it such accounts get
	// `MFA_REQUIRED` (after the password was checked); resubmit the same
	// request with the code.
	MfaCode  *string `json:"mfaCode,omitempty"`
	Password string  `json:"password"`
}

// Member defines model for Member.
type Member struct {
	// JoinedAt UTC RFC 3339 timestamp
	JoinedAt Timestamp    `json:"joinedAt"`
	Role     ClubRole     `json:"role"`
	Status   MemberStatus `json:"status"`
	UserId   Uuid         `json:"userId"`
	Username string       `json:"username"`
}

// MemberBalance defines model for MemberBalance.
type MemberBalance struct {
	// TableBalance Integer amount of virtual chips (no monetary value).
	TableBalance ChipAmount `json:"tableBalance"`
	UserId       Uuid       `json:"userId"`
	Username     string     `json:"username"`

	// WalletBalance Integer amount of virtual chips (no monetary value).
	WalletBalance ChipAmount `json:"walletBalance"`
}

// MemberBalancePage defines model for MemberBalancePage.
type MemberBalancePage struct {
	Items      []MemberBalance `json:"items"`
	NextCursor *string         `json:"nextCursor"`
}

// MemberPage defines model for MemberPage.
type MemberPage struct {
	Items      []Member `json:"items"`
	NextCursor *string  `json:"nextCursor"`
}

// MemberStatus defines model for MemberStatus.
type MemberStatus string

// MfaCodeRequest defines model for MfaCodeRequest.
type MfaCodeRequest struct {
	Code string `json:"code"`
}

// MfaRecoveryCodes defines model for MfaRecoveryCodes.
type MfaRecoveryCodes struct {
	RecoveryCodes []string `json:"recoveryCodes"`
}

// MfaStatus defines model for MfaStatus.
type MfaStatus struct {
	Enabled bool `json:"enabled"`

	// Pending A secret was issued but not confirmed yet.
	Pending           bool `json:"pending"`
	RecoveryCodesLeft int  `json:"recoveryCodesLeft"`

	// SessionVerified The current session was established with a second factor.
	SessionVerified bool `json:"sessionVerified"`
}

// PlatformOverview defines model for PlatformOverview.
type PlatformOverview struct {
	Clubs struct {
		Active    int `json:"active"`
		Suspended int `json:"suspended"`
		Total     int `json:"total"`
	} `json:"clubs"`

	// GeneratedAt UTC RFC 3339 timestamp
	GeneratedAt Timestamp `json:"generatedAt"`
	Hands       struct {
		CompletedLast24h int `json:"completedLast24h"`
		InProgress       int `json:"inProgress"`
		VoidedLast24h    int `json:"voidedLast24h"`
	} `json:"hands"`
	Ledger struct {
		// InvariantViolations Must always be 0; anything else pages the on-call (docs/runbooks).
		InvariantViolations int `json:"invariantViolations"`
	} `json:"ledger"`
	Risk struct {
		HighSeverityOpen int `json:"highSeverityOpen"`
		OpenEvents       int `json:"openEvents"`
	} `json:"risk"`
	Sessions struct {
		Active int `json:"active"`
	} `json:"sessions"`
	Tables struct {
		Open          int `json:"open"`
		SeatedPlayers int `json:"seatedPlayers"`
	} `json:"tables"`
	Users struct {
		PlatformAdmins int `json:"platformAdmins"`
		Suspended      int `json:"suspended"`
		Total          int `json:"total"`
	} `json:"users"`
}

// PlatformRole defines model for PlatformRole.
type PlatformRole string

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken *string `json:"refreshToken,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DeviceId *string             `json:"deviceId,omitempty"`
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Username string              `json:"username"`
}

// ReversalRequest defines model for ReversalRequest.
type ReversalRequest struct {
	Note string `json:"note"`
}

// ReviewRiskEventRequest defines model for ReviewRiskEventRequest.
type ReviewRiskEventRequest struct {
	Disposition ReviewRiskEventRequestDisposition `json:"disposition"`
	Note        string                            `json:"note"`
}

// ReviewRiskEventRequestDisposition defines model for ReviewRiskEventRequest.Disposition.
type ReviewRiskEventRequestDisposition string

// RiskEvent defines model for RiskEvent.
type RiskEvent struct {
	ClubId *openapi_types.UUID `json:"clubId"`

	// CreatedAt UTC RFC 3339 timestamp
	CreatedAt          Timestamp              `json:"createdAt"`
	Disposition        *RiskEventDisposition  `json:"disposition"`
	EvidenceRefs       []interface{}          `json:"evidenceRefs"`
	FeatureValues      map[string]interface{} `json:"featureValues"`
	Id                 Uuid                   `json:"id"`
	ReviewNote         *string                `json:"reviewNote"`
	ReviewedAt         *time.Time             `json:"reviewedAt"`
	ReviewedBy         *openapi_types.UUID    `json:"reviewedBy"`
	ReviewedByUsername *string                `json:"reviewedByUsername"`
	Score              int                    `json:"score"`
	Severity           RiskEventSeverity      `json:"severity"`
	SubjectUserId      *openapi_types.UUID    `json:"subjectUserId"`
	SubjectUsername    *string                `json:"subjectUsername"`
	Type               string                 `json:"type"`
}

// RiskEventDisposition defines model for RiskEvent.Disposition.
type RiskEventDisposition string

// RiskEventSeverity defines model for RiskEvent.Severity.
type RiskEventSeverity string

// RiskEventPage defines model for RiskEventPage.
type RiskEventPage struct {
	Items      []RiskEvent `json:"items"`
	NextCursor *string     `json:"nextCursor"`
}

// SeatRequest defines model for SeatRequest.
type SeatRequest struct {
	// BuyIn Integer amount of virtual chips (no monetary value).
	BuyIn ChipAmount `json:"buyIn"`

	// SeatNo Omit to take the first free seat.
	SeatNo *int `json:"seatNo,omitempty"`
}

// SeatResult defines model for SeatResult.
type SeatResult struct {
	SeatNo int   `json:"seatNo"`
	Seq    int64 `json:"seq"`

	// Stack Integer amount of virtual chips (no monetary value).
	Stack   ChipAmount `json:"stack"`
	TableId Uuid       `json:"tableId"`
}

// Session defines model for Session.
type Session struct {
	// CreatedAt UTC RFC 3339 timestamp
	CreatedAt Timestamp `json:"createdAt"`
	Current   bool      `json:"current"`
	DeviceId  *string   `json:"deviceId"`

	// ExpiresAt UTC RFC 3339 timestamp
	ExpiresAt Timestamp `json:"expiresAt"`
	Id        Uuid      `json:"id"`

	// LastUsedAt UTC RFC 3339 timestamp
	LastUsedAt Timestamp `json:"lastUsedAt"`
	UserAgent  *string   `json:"userAgent"`
}

// SessionList defines model for SessionList.
type SessionList struct {
	Items []Session `json:"items"`
}

// Table defines model for Table.
type Table struct {
	ActionTimeoutSec int `json:"actionTimeoutSec"`

	// BigBlind Integer amount of virtual chips (no monetary value).
	BigBlind ChipAmount `json:"bigBlind"`

	// BuyInMax Integer amount of virtual chips (no monetary value).
	BuyInMax ChipAmount `json:"buyInMax"`

	// BuyInMin Integer amount of virtual chips (no monetary value).
	BuyInMin ChipAmount `json:"buyInMin"`
	ClubId   Uuid       `json:"clubId"`

	// CreatedAt UTC RFC 3339 timestamp
	CreatedAt Timestamp `json:"createdAt"`
	CreatedBy Uuid      `json:"createdBy"`

	// GameType NLHE = No-Limit Texas Hold'em (2 hole cards). PLO = Pot-Limit Omaha
	// (4 hole cards; a hand uses exactly two of them and three board cards;
	// bets and raises are capped at the pot).
	GameType    externalRef0.GameType `json:"gameType"`
	Id          Uuid                  `json:"id"`
	MaxSeats    int                   `json:"maxSeats"`
	Name        string                `json:"name"`
	SeatedCount int                   `json:"seatedCount"`

	// SmallBlind Integer amount of virtual chips (no monetary value).
	SmallBlind ChipAmount  `json:"smallBlind"`
	Status     TableStatus `json:"status"`

	// TournamentId Set for a tournament's tables (seats are assigned by the tournament).
	TournamentId *openapi_types.UUID `json:"tournamentId"`
}

// TableStatus defines model for Table.Status.
type TableStatus string

// TableDetail defines model for TableDetail.
type TableDetail struct {
	ActionTimeoutSec int `json:"actionTimeoutSec"`

	// BigBlind Integer amount of virtual chips (no monetary value).
	BigBlind ChipAmount `json:"bigBlind"`

	// BuyInMax Integer amount of virtual chips (no monetary value).
	BuyInMax ChipAmount `json:"buyInMax"`

	// BuyInMin Integer amount of virtual chips (no monetary value).
	BuyInMin ChipAmount `json:"buyInMin"`
	ClubId   Uuid       `json:"clubId"`

	// CreatedAt UTC RFC 3339 timestamp
	CreatedAt Timestamp `json:"createdAt"`
	CreatedBy Uuid      `json:"createdBy"`

	// GameType NLHE = No-Limit Texas Hold'em (2 hole cards). PLO = Pot-Limit Omaha
	// (4 hole cards; a hand uses exactly two of them and three board cards;
	// bets and raises are capped at the pot).
	GameType    externalRef0.GameType `json:"gameType"`
	Id          Uuid                  `json:"id"`
	MaxSeats    int                   `json:"maxSeats"`
	Name        string                `json:"name"`
	SeatedCount int                   `json:"seatedCount"`
	Seats       []TableSeat           `json:"seats"`

	// SmallBlind Integer amount of virtual chips (no monetary value).
	SmallBlind ChipAmount        `json:"smallBlind"`
	Status     TableDetailStatus `json:"status"`

	// TournamentId Set for a tournament's tables (seats are assigned by the tournament).
	TournamentId *openapi_types.UUID `json:"tournamentId"`
}

// TableDetailStatus defines model for TableDetail.Status.
type TableDetailStatus string

// TableList defines model for TableList.
type TableList struct {
	Items []Table `json:"items"`
}

// TableSeat defines model for TableSeat.
type TableSeat struct {
	SeatNo     int  `json:"seatNo"`
	SittingOut bool `json:"sittingOut"`

	// Stack Integer amount of virtual chips (no monetary value).
	Stack    ChipAmount `json:"stack"`
	UserId   Uuid       `json:"userId"`
	Username string     `json:"username"`
}

// Timestamp UTC RFC 3339 timestamp
type Timestamp = time.Time

// TotpEnrollment defines model for TotpEnrollment.
type TotpEnrollment struct {
	// OtpauthUri otpauth://totp/... URI (QR code content).
	OtpauthUri string `json:"otpauthUri"`

	// Secret Base32 secret for manual entry in an authenticator app.
	Secret string `json:"secret"`
}

// Tournament No additionalProperties restriction because TournamentDetail extends it (allOf).
type Tournament struct {
	ActionTimeoutSec int `json:"actionTimeoutSec"`

	// BuyIn Integer amount of virtual chips (no monetary value).
	BuyIn  ChipAmount `json:"buyIn"`
	ClubId Uuid       `json:"clubId"`

	// CreatedAt UTC RFC 3339 timestamp
	CreatedAt  Timestamp  `json:"createdAt"`
	FinishedAt *time.Time `json:"finishedAt"`

	// GameType NLHE = No-Limit Texas Hold'em (2 hole cards). PLO = Pot-Limit Omaha
	// (4 hole cards; a hand uses exactly two of them and three board cards;
	// bets and raises are capped at the pot).
	GameType         externalRef0.GameType `json:"gameType"`
	Id               Uuid                  `json:"id"`
	LevelDurationSec int                   `json:"levelDurationSec"`
	MaxPlayers       int                   `json:"maxPlayers"`
	MinPlayers       int                   `json:"minPlayers"`
	Name             string                `json:"name"`

	// PrizePool Integer amount of virtual chips (no monetary value).
	PrizePool ChipAmount `json:"prizePool"`

	// Registered Whether the viewer holds an active registration / entry.
	Registered bool `json:"registered"`

	// RegisteredCount Active registrations (entrants once started).
	RegisteredCount int `json:"registeredCount"`
	SeatsPerTable   int `json:"seatsPerTable"`

	// StartMode SIT_AND_GO starts when maxPlayers registered; SCHEDULED at startsAt (cancelled and refunded if fewer than minPlayers).
	StartMode TournamentStartMode `json:"startMode"`
	StartedAt *time.Time          `json:"startedAt"`

	// StartingStack Tournament chips each player starts with (not club chips).
	StartingStack int64            `json:"startingStack"`
	StartsAt      *time.Time       `json:"startsAt"`
	Status        TournamentStatus `json:"status"`
}

// TournamentDetail defines model for TournamentDetail.
type TournamentDetail struct {
	ActionTimeoutSec int `json:"actionTimeoutSec"`

	// BuyIn Integer amount of virtual chips (no monetary value).
	BuyIn  ChipAmount `json:"buyIn"`
	ClubId Uuid       `json:"clubId"`

	// CreatedAt UTC RFC 3339 timestamp
	CreatedAt Timestamp `json:"createdAt"`

	// CurrentLevel The level in effect for new hands (null before the start and after the end).
	CurrentLevel *struct {
		// BigBlind Integer amount of virtual chips (no monetary value).
		BigBlind ChipAmount `json:"bigBlind"`
		Level    int        `json:"level"`

		// SmallBlind Integer amount of virtual chips (no monetary value).
		SmallBlind ChipAmount `json:"smallBlind"`
	} `json:"currentLevel"`
	Entrants   []TournamentEntrant `json:"entrants"`
	FinishedAt *time.Time          `json:"finishedAt"`

	// GameType NLHE = No-Limit Texas Hold'em (2 hole cards). PLO = Pot-Limit Omaha
	// (4 hole cards; a hand uses exactly two of them and three board cards;
	// bets and raises are capped at the pot).
	GameType         externalRef0.GameType `json:"gameType"`
	Id               Uuid                  `json:"id"`
	LevelDurationSec int                   `json:"levelDurationSec"`
	LevelEndsAt      *time.Time            `json:"levelEndsAt"`

	// Levels The first levels of the blind schedule (later levels keep doubling).
	Levels     []BlindLevel        `json:"levels"`
	MaxPlayers int                 `json:"maxPlayers"`
	MinPlayers int                 `json:"minPlayers"`
	MyTableId  *openapi_types.UUID `json:"myTableId"`
	Name       string              `json:"name"`

	// Payouts Prizes by place (projected from current registrations before the start).
	Payouts     []TournamentPayout `json:"payouts"`
	PlayersLeft int                `json:"playersLeft"`

	// PrizePool Integer amount of virtual chips (no monetary value).
	PrizePool ChipAmount `json:"prizePool"`

	// Registered Whether the viewer holds an active registration / entry.
	Registered bool `json:"registered"`

	// RegisteredCount Active registrations (entrants once started).
	RegisteredCount int `json:"registeredCount"`
	SeatsPerTable   int `json:"seatsPerTable"`

	// StartMode SIT_AND_GO starts when maxPlayers registered; SCHEDULED at startsAt (cancelled and refunded if fewer than minPlayers).
	StartMode TournamentStartMode `json:"startMode"`
	StartedAt *time.Time          `json:"startedAt"`

	// StartingStack Tournament chips each player starts with (not club chips).
	StartingStack int64            `json:"startingStack"`
	StartsAt      *time.Time       `json:"startsAt"`
	Status        TournamentStatus `json:"status"`
}

// TournamentEntrant defines model for TournamentEntrant.
type TournamentEntrant struct {
	// Place Finishing place (null while still playing); tied players share a place.
	Place *int `json:"place"`

	// Prize Integer amount of virtual chips (no monetary value).
	Prize ChipAmount `json:"prize"`

	// Stack Tournament chips at the last completed hand (null when out or moving).
	Stack *int64 `json:"stack"`

	// TableId Current (or destination, while moving) table.
	TableId  *openapi_types.UUID `json:"tableId"`
	UserId   Uuid                `json:"userId"`
	Username string              `json:"username"`
}

// TournamentList defines model for TournamentList.
type TournamentList struct {
	Items []Tournament `json:"items"`
}

// TournamentPayout defines model for TournamentPayout.
type TournamentPayout struct {
	// Amount Integer amount of virtual chips (no monetary value).
	Amount ChipAmount `json:"amount"`
	Place  int        `json:"place"`
}

// TournamentStartMode SIT_AND_GO starts when maxPlayers registered; SCHEDULED at startsAt (cancelled and refunded if fewer than minPlayers).
type TournamentStartMode string

// TournamentStatus defines model for TournamentStatus.
type TournamentStatus string

// TransferOwnershipRequest defines model for TransferOwnershipRequest.
type TransferOwnershipRequest struct {
	UserId Uuid `json:"userId"`
}

// UpdateAccountStatusRequest defines model for UpdateAccountStatusRequest.
type UpdateAccountStatusRequest struct {
	// Reason Recorded in the audit log.
	Reason string                           `json:"reason"`
	Status UpdateAccountStatusRequestStatus `json:"status"`
}

// UpdateAccountStatusRequestStatus defines model for UpdateAccountStatusRequest.Status.
type UpdateAccountStatusRequestStatus string

// UpdateClubRequest defines model for UpdateClubRequest.
type UpdateClubRequest struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// UpdateMemberRequest defines model for UpdateMemberRequest.
type UpdateMemberRequest struct {
	Role   *UpdateMemberRequestRole   `json:"role,omitempty"`
	Status *UpdateMemberRequestStatus `json:"status,omitempty"`
}

// UpdateMemberRequestRole defines model for UpdateMemberRequest.Role.
type UpdateMemberRequestRole string

// UpdateMemberRequestStatus defines model for UpdateMemberRequest.Status.
type UpdateMemberRequestStatus string

// User defines model for User.
type User struct {
	// CreatedAt UTC RFC 3339 timestamp
	CreatedAt    Timestamp           `json:"createdAt"`
	Email        openapi_types.Email `json:"email"`
	Id           Uuid                `json:"id"`
	PlatformRole PlatformRole        `json:"platformRole"`
	Status       UserStatus          `json:"status"`
	Username     string              `json:"username"`
}

// UserStatus defines model for UserStatus.
type UserStatus string

// Uuid defines model for Uuid.
type Uuid = openapi_types.UUID

// Wallet defines model for Wallet.
type Wallet struct {
	// Balance Integer amount of virtual chips (no monetary value).
	Balance ChipAmount `json:"balance"`
	ClubId  Uuid       `json:"clubId"`
	UserId  Uuid       `json:"userId"`
}

// WalletEntry defines model for WalletEntry.
type WalletEntry struct {
	// Amount Integer amount of virtual chips (no monetary value).
	Amount ChipAmount `json:"amount"`

	// BalanceAfter Integer amount of virtual chips (no monetary value).
	BalanceAfter ChipAmount `json:"balanceAfter"`

	// CreatedAt UTC RFC 3339 timestamp
	CreatedAt     Timestamp  `json:"createdAt"`
	EntryId       Uuid       `json:"entryId"`
	Kind          LedgerKind `json:"kind"`
	ReferenceId   *string    `json:"referenceId"`
	ReferenceType *string    `json:"referenceType"`
	TxId          Uuid       `json:"txId"`
}

// WalletEntryPage defines model for WalletEntryPage.
type WalletEntryPage struct {
	Items      []WalletEntry `json:"items"`
	NextCursor *string       `json:"nextCursor"`
}

// AuthTransport defines model for AuthTransport.
type AuthTransport string

// ClubId defines model for ClubId.
type ClubId = Uuid

// Cursor defines model for Cursor.
type Cursor = string

// HandId defines model for HandId.
type HandId = Uuid

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Limit defines model for Limit.
type Limit = int

// RequestId defines model for RequestId.
type RequestId = string

// TableId defines model for TableId.
type TableId = Uuid

// TournamentId defines model for TournamentId.
type TournamentId = Uuid

// Error defines model for Error.
type Error = ErrorEnvelope

// AdminAuditLogParams defines parameters for AdminAuditLog.
type AdminAuditLogParams struct {
	ClubId      *Uuid   `form:"clubId,omitempty" json:"clubId,omitempty"`
	ActorUserId *Uuid   `form:"actorUserId,omitempty" json:"actorUserId,omitempty"`
	Action      *string `form:"action,omitempty" json:"action,omitempty"`
	Limit       *Limit  `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous page's `nextCursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// AdminSearchClubsParams defines parameters for AdminSearchClubs.
type AdminSearchClubsParams struct {
	// Q Case-insensitive prefix (username/email for users, name for clubs).
	Q     *string `form:"q,omitempty" json:"q,omitempty"`
	Limit *Limit  `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous page's `nextCursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// AdminRiskEventsParams defines parameters for AdminRiskEvents.
type AdminRiskEventsParams struct {
	Status *AdminRiskEventsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *Limit                       `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous page's `nextCursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// AdminRiskEventsParamsStatus defines parameters for AdminRiskEvents.
type AdminRiskEventsParamsStatus string

// AdminSearchUsersParams defines parameters for AdminSearchUsers.
type AdminSearchUsersParams struct {
	// Q Case-insensitive prefix (username/email for users, name for clubs).
	Q     *string `form:"q,omitempty" json:"q,omitempty"`
	Limit *Limit  `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous page's `nextCursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// LoginParams defines parameters for Login.
type LoginParams struct {
	// XAuthTransport `cookie` makes the API deliver the refresh token in an HttpOnly
	// SameSite=Strict cookie (`kof_rt`, path `/v1/auth`) instead of the body.
	XAuthTransport *LoginParamsXAuthTransport `json:"X-Auth-Transport,omitempty"`
}

// LoginParamsXAuthTransport defines parameters for Login.
type LoginParamsXAuthTransport string

// RefreshParams defines parameters for Refresh.
type RefreshParams struct {
	// XAuthTransport `cookie` makes the API deliver the refresh token in an HttpOnly
	// SameSite=Strict cookie (`kof_rt`, path `/v1/auth`) instead of the body.
	XAuthTransport *RefreshParamsXAuthTransport `json:"X-Auth-Transport,omitempty"`
}

// RefreshParamsXAuthTransport defines parameters for Refresh.
type RefreshParamsXAuthTransport string

// RegisterParams defines parameters for Register.
type RegisterParams struct {
	// XAuthTransport `cookie` makes the API deliver the refresh token in an HttpOnly
	// SameSite=Strict cookie (`kof_rt`, path `/v1/auth`) instead of the body.
	XAuthTransport *RegisterParamsXAuthTransport `json:"X-Auth-Transport,omitempty"`
}

// RegisterParamsXAuthTransport defines parameters for Register.
type RegisterParamsXAuthTransport string

// CreateClubParams defines parameters for CreateClub.
type CreateClubParams struct {
	// IdempotencyKey Unique key making a retried state-changing request a no-op.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListClubAuditLogParams defines parameters for ListClubAuditLog.
type ListClubAuditLogParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous page's `nextCursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// DeductChipsParams defines parameters for DeductChips.
type DeductChipsParams struct {
	// IdempotencyKey Required for chip movements; retries with the same key never move chips twice.
	IdempotencyKey string `json:"Idempotency-Key"`
}

// GrantChipsParams defines parameters for GrantChips.
type GrantChipsParams struct {
	// IdempotencyKey Required for chip movements; retries with the same key never move chips twice.
	IdempotencyKey string `json:"Idempotency-Key"`
}

// ListClubHandsParams defines parameters for ListClubHands.
type ListClubHandsParams struct {
	TableId *Uuid  `form:"tableId,omitempty" json:"tableId,omitempty"`
	Limit   *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous page's `nextCursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateClubInviteParams defines parameters for CreateClubInvite.
type CreateClubInviteParams struct {
	// IdempotencyKey Unique key making a retried state-changing request a no-op.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListMemberBalancesParams defines parameters for ListMemberBalances.
type ListMemberBalancesParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous page's `nextCursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListLedgerTransactionsParams defines parameters for ListLedgerTransactions.
type ListLedgerTransactionsParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous page's `nextCursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ReverseLedgerTransactionParams defines parameters for ReverseLedgerTransaction.
type ReverseLedgerTransactionParams struct {
	// IdempotencyKey Required for chip movements; retries with the same key never move chips twice.
	IdempotencyKey string `json:"Idempotency-Key"`
}

// ListClubMembersParams defines parameters for ListClubMembers.
type ListClubMembersParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous page's `nextCursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Status Filter by status (staff only; members always see ACTIVE).
	Status *MemberStatus `form:"status,omitempty" json:"status,omitempty"`
}

// CreateTableParams defines parameters for CreateTable.
type CreateTableParams struct {
	// IdempotencyKey Unique key making a retried state-changing request a no-op.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CreateTournamentParams defines parameters for CreateTournament.
type CreateTournamentParams struct {
	// IdempotencyKey Unique key making a retried state-changing request a no-op.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListMyWalletEntriesParams defines parameters for ListMyWalletEntries.
type ListMyWalletEntriesParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous page's `nextCursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListMyHandsParams defines parameters for ListMyHands.
type ListMyHandsParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from a previous page's `nextCursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// LeaveTableParams defines parameters for LeaveTable.
type LeaveTableParams struct {
	// IdempotencyKey Unique key making a retried state-changing request a no-op.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// TakeSeatParams defines parameters for TakeSeat.
type TakeSeatParams struct {
	// IdempotencyKey Unique key making a retried state-changing request a no-op.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// RegisterForTournamentParams defines parameters for RegisterForTournament.
type RegisterForTournamentParams struct {
	// IdempotencyKey Unique key making a retried state-changing request a no-op.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// AdminSetClubStatusJSONRequestBody defines body for AdminSetClubStatus for application/json ContentType.
type AdminSetClubStatusJSONRequestBody = UpdateAccountStatusRequest

// AdminReviewRiskEventJSONRequestBody defines body for AdminReviewRiskEvent for application/json ContentType.
type AdminReviewRiskEventJSONRequestBody = ReviewRiskEventRequest

// AdminSetUserStatusJSONRequestBody defines body for AdminSetUserStatus for application/json ContentType.
type AdminSetUserStatusJSONRequestBody = UpdateAccountStatusRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateClubJSONRequestBody defines body for CreateClub for application/json ContentType.
type CreateClubJSONRequestBody = CreateClubRequest

// JoinClubByCodeJSONRequestBody defines body for JoinClubByCode for application/json ContentType.
type JoinClubByCodeJSONRequestBody = JoinClubRequest

// UpdateClubJSONRequestBody defines body for UpdateClub for application/json ContentType.
type UpdateClubJSONRequestBody = UpdateClubRequest

// DeductChipsJSONRequestBody defines body for DeductChips for application/json ContentType.
type DeductChipsJSONRequestBody = ChipMovementRequest

// GrantChipsJSONRequestBody defines body for GrantChips for application/json ContentType.
type GrantChipsJSONRequestBody = ChipMovementRequest

// CreateClubInviteJSONRequestBody defines body for CreateClubInvite for application/json ContentType.
type CreateClubInviteJSONRequestBody = CreateInviteRequest

// JoinClubJSONRequestBody defines body for JoinClub for application/json ContentType.
type JoinClubJSONRequestBody = JoinClubRequest

// ReverseLedgerTransactionJSONRequestBody defines body for ReverseLedgerTransaction for application/json ContentType.
type ReverseLedgerTransactionJSONRequestBody = ReversalRequest

// UpdateClubMemberJSONRequestBody defines body for UpdateClubMember for application/json ContentType.
type UpdateClubMemberJSONRequestBody = UpdateMemberRequest

// CreateTableJSONRequestBody defines body for CreateTable for application/json ContentType.
type CreateTableJSONRequestBody = CreateTableRequest

// CreateTournamentJSONRequestBody defines body for CreateTournament for application/json ContentType.
type CreateTournamentJSONRequestBody = CreateTournamentRequest

// TransferClubOwnershipJSONRequestBody defines body for TransferClubOwnership for application/json ContentType.
type TransferClubOwnershipJSONRequestBody = TransferOwnershipRequest

// ConfirmTotpEnrollmentJSONRequestBody defines body for ConfirmTotpEnrollment for application/json ContentType.
type ConfirmTotpEnrollmentJSONRequestBody = MfaCodeRequest

// DisableTotpJSONRequestBody defines body for DisableTotp for application/json ContentType.
type DisableTotpJSONRequestBody = MfaCodeRequest

// TakeSeatJSONRequestBody defines body for TakeSeat for application/json ContentType.
type TakeSeatJSONRequestBody = SeatRequest
