// Package controlapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package controlapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	ErrorCodeACCOUNTSUSPENDED         ErrorCode = "ACCOUNT_SUSPENDED"
	ErrorCodeACTIONALREADYPROCESSED   ErrorCode = "ACTION_ALREADY_PROCESSED"
	ErrorCodeALREADYCLUBMEMBER        ErrorCode = "ALREADY_CLUB_MEMBER"
	ErrorCodeALREADYSEATED            ErrorCode = "ALREADY_SEATED"
	ErrorCodeAUTHINVALIDCREDENTIALS   ErrorCode = "AUTH_INVALID_CREDENTIALS"
	ErrorCodeAUTHREFRESHINVALID       ErrorCode = "AUTH_REFRESH_INVALID"
	ErrorCodeAUTHREFRESHREUSED        ErrorCode = "AUTH_REFRESH_REUSED"
	ErrorCodeAUTHREQUIRED             ErrorCode = "AUTH_REQUIRED"
	ErrorCodeAUTHSESSIONREVOKED       ErrorCode = "AUTH_SESSION_REVOKED"
	ErrorCodeAUTHTOKENEXPIRED         ErrorCode = "AUTH_TOKEN_EXPIRED"
	ErrorCodeAUTHTOKENINVALID         ErrorCode = "AUTH_TOKEN_INVALID"
	ErrorCodeCLUBBANNED               ErrorCode = "CLUB_BANNED"
	ErrorCodeCLUBNOTFOUND             ErrorCode = "CLUB_NOT_FOUND"
	ErrorCodeCONFLICT                 ErrorCode = "CONFLICT"
	ErrorCodeEMAILTAKEN               ErrorCode = "EMAIL_TAKEN"
	ErrorCodeFORBIDDEN                ErrorCode = "FORBIDDEN"
	ErrorCodeHANDNOTACTIVE            ErrorCode = "HAND_NOT_ACTIVE"
	ErrorCodeHANDNOTFOUND             ErrorCode = "HAND_NOT_FOUND"
	ErrorCodeIDEMPOTENCYCONFLICT      ErrorCode = "IDEMPOTENCY_CONFLICT"
	ErrorCodeILLEGALACTION            ErrorCode = "ILLEGAL_ACTION"
	ErrorCodeINSUFFICIENTCHIPS        ErrorCode = "INSUFFICIENT_CHIPS"
	ErrorCodeINTERNAL                 ErrorCode = "INTERNAL"
	ErrorCodeINVALIDBUYIN             ErrorCode = "INVALID_BUY_IN"
	ErrorCodeINVALIDRAISE             ErrorCode = "INVALID_RAISE"
	ErrorCodeINVITEINVALID            ErrorCode = "INVITE_INVALID"
	ErrorCodeLEDGERINVARIANTVIOLATION ErrorCode = "LEDGER_INVARIANT_VIOLATION"
	ErrorCodeNOTCLUBMEMBER            ErrorCode = "NOT_CLUB_MEMBER"
	ErrorCodeNOTFOUND                 ErrorCode = "NOT_FOUND"
	ErrorCodeNOTYOURTURN              ErrorCode = "NOT_YOUR_TURN"
	ErrorCodePLAYERNOTSEATED          ErrorCode = "PLAYER_NOT_SEATED"
	ErrorCodeRATELIMITED              ErrorCode = "RATE_LIMITED"
	ErrorCodeROLECHANGENOTALLOWED     ErrorCode = "ROLE_CHANGE_NOT_ALLOWED"
	ErrorCodeSEATTAKEN                ErrorCode = "SEAT_TAKEN"
	ErrorCodeSERVICEUNAVAILABLE       ErrorCode = "SERVICE_UNAVAILABLE"
	ErrorCodeSTALEGAMESTATE           ErrorCode = "STALE_GAME_STATE"
	ErrorCodeTABLECLOSED              ErrorCode = "TABLE_CLOSED"
	ErrorCodeTABLEFULL                ErrorCode = "TABLE_FULL"
	ErrorCodeTABLENOTFOUND            ErrorCode = "TABLE_NOT_FOUND"
	ErrorCodeTABLEUNAVAILABLE         ErrorCode = "TABLE_UNAVAILABLE"
	ErrorCodeTOURNAMENTNOTOPEN        ErrorCode = "TOURNAMENT_NOT_OPEN"
	ErrorCodeUSERNAMETAKEN            ErrorCode = "USERNAME_TAKEN"
	ErrorCodeVALIDATIONFAILED         ErrorCode = "VALIDATION_FAILED"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeACCOUNTSUSPENDED:
		return true
	case ErrorCodeACTIONALREADYPROCESSED:
		return true
	case ErrorCodeALREADYCLUBMEMBER:
		return true
	case ErrorCodeALREADYSEATED:
		return true
	case ErrorCodeAUTHINVALIDCREDENTIALS:
		return true
	case ErrorCodeAUTHREFRESHINVALID:
		return true
	case ErrorCodeAUTHREFRESHREUSED:
		return true
	case ErrorCodeAUTHREQUIRED:
		return true
	case ErrorCodeAUTHSESSIONREVOKED:
		return true
	case ErrorCodeAUTHTOKENEXPIRED:
		return true
	case ErrorCodeAUTHTOKENINVALID:
		return true
	case ErrorCodeCLUBBANNED:
		return true
	case ErrorCodeCLUBNOTFOUND:
		return true
	case ErrorCodeCONFLICT:
		return true
	case ErrorCodeEMAILTAKEN:
		return true
	case ErrorCodeFORBIDDEN:
		return true
	case ErrorCodeHANDNOTACTIVE:
		return true
	case ErrorCodeHANDNOTFOUND:
		return true
	case ErrorCodeIDEMPOTENCYCONFLICT:
		return true
	case ErrorCodeILLEGALACTION:
		return true
	case ErrorCodeINSUFFICIENTCHIPS:
		return true
	case ErrorCodeINTERNAL:
		return true
	case ErrorCodeINVALIDBUYIN:
		return true
	case ErrorCodeINVALIDRAISE:
		return true
	case ErrorCodeINVITEINVALID:
		return true
	case ErrorCodeLEDGERINVARIANTVIOLATION:
		return true
	case ErrorCodeNOTCLUBMEMBER:
		return true
	case ErrorCodeNOTFOUND:
		return true
	case ErrorCodeNOTYOURTURN:
		return true
	case ErrorCodePLAYERNOTSEATED:
		return true
	case ErrorCodeRATELIMITED:
		return true
	case ErrorCodeROLECHANGENOTALLOWED:
		return true
	case ErrorCodeSEATTAKEN:
		return true
	case ErrorCodeSERVICEUNAVAILABLE:
		return true
	case ErrorCodeSTALEGAMESTATE:
		return true
	case ErrorCodeTABLECLOSED:
		return true
	case ErrorCodeTABLEFULL:
		return true
	case ErrorCodeTABLENOTFOUND:
		return true
	case ErrorCodeTABLEUNAVAILABLE:
		return true
	case ErrorCodeTOURNAMENTNOTOPEN:
		return true
	case ErrorCodeUSERNAMETAKEN:
		return true
	case ErrorCodeVALIDATIONFAILED:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	HealthStatusStatusDraining    HealthStatusStatus = "draining"
	HealthStatusStatusOk          HealthStatusStatus = "ok"
	HealthStatusStatusUnavailable HealthStatusStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case HealthStatusStatusDraining:
		return true
	case HealthStatusStatusOk:
		return true
	case HealthStatusStatusUnavailable:
		return true
	default:
		return false
	}
}

// ChipAmount Integer amount of virtual chips (no monetary value).
type ChipAmount = int64

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	// Code Stable machine-readable error codes shared by HTTP and realtime APIs.
	// Clients must branch on `code`, never on `message`.
	Code    ErrorCode               `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable summary (not for programmatic use).
	Message   string `json:"message"`
	RequestId string `json:"requestId"`
}

// ErrorCode Stable machine-readable error codes shared by HTTP and realtime APIs.
// Clients must branch on `code`, never on `message`.
type ErrorCode string

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error ErrorBody `json:"error"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Checks  *map[string]string `json:"checks,omitempty"`
	Service string             `json:"service"`
	Status  HealthStatusStatus `json:"status"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// Timestamp UTC RFC 3339 timestamp
type Timestamp = time.Time

// Uuid defines model for Uuid.
type Uuid = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// RequestId defines model for RequestId.
type RequestId = string

// Error defines model for Error.
type Error = ErrorEnvelope
